---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel7-fips-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-072f43ee3eaa2f219
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: t3.large
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../../fips-tests/
  additional_files_or_dirs:
    - ../psmdb/tests/
  options:
    verbose: true
    s: true
    junitxml: rhel7-fips-report.xml
scenario:
  name: rhel7-fips
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
