---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: PML-ujammy-arm-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: "${MOLECULE_UJAMMY_ARM_AMI:-ami-07534e46c9116761b}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: c6g.large
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    prepare: ../../playbooks/prepare.yml
    destroy: ../../../../playbooks/destroy.yml
    converge: ../../playbooks/ubuntu.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: ubuntu-jammy-arm
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
