---
- name: Install required packages
  yum:
    state: present
    validate_certs: no
    disable_gpg_check: yes
    name:
    - openldap
    - openldap-servers
    - openldap-clients
    - python-ldap
    - jq
  when: ansible_distribution_major_version <= "7"

- name: Fetch CentOS gpg key
  get_url:
    url: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
    dest: /tmp/RPM-GPG-KEY-CentOS-Official
  retries: 5
  delay: 10
  register: result
  until: result.failed == false
  when: ansible_distribution_major_version == "8"

- name: Import CentOS gpg key
  rpm_key:
    state: present
    key: /tmp/RPM-GPG-KEY-CentOS-Official
  when: ansible_distribution_major_version == "8"

- name: Install required packages
  yum:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3-ldap
    - gcc
    - python3-devel
    - jq
  when: ansible_distribution_major_version >= "8"

- name: Install required packages
  yum:
    name: "{{packages}}"
    state: present
  vars:
    packages:
    - http://vault.centos.org/centos/8-stream/BaseOS/{{ ansible_architecture }}/os/Packages/openldap-2.4.46-18.el8.{{ ansible_architecture }}.rpm
    - http://vault.centos.org/centos/8-stream/BaseOS/{{ ansible_architecture }}/os/Packages/openldap-devel-2.4.46-18.el8.{{ ansible_architecture }}.rpm
    - http://vault.centos.org/centos/8-stream/BaseOS/{{ ansible_architecture }}/os/Packages/openldap-clients-2.4.46-18.el8.{{ ansible_architecture }}.rpm
    - http://vault.centos.org/centos/8-stream/PowerTools/{{ ansible_architecture }}/os/Packages/openldap-servers-2.4.46-18.el8.{{ ansible_architecture }}.rpm
  when: ansible_distribution_major_version == "8"

- name: Import epel gpg key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  when: ansible_distribution_major_version == "9"

- name: Install epel repo
  yum:
    name: "{{packages}}"
    state: present
  vars:
    packages:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  when: ansible_distribution_major_version == "9"

#- name: Install additional epel repo for x86_64
#  yum:
#    name: "{{packages}}"
#    state: present
#  vars:
#    packages:
#    - https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
#  when: ansible_distribution_major_version == "9" and ansible_architecture == "x86_64"

- name: Install required packages
  yum:
    state: present
    name:
    - openldap
    - openldap-devel
    - openldap-servers
    - openldap-clients
  when: ansible_distribution_major_version == "9"

- name: Install required packages
  yum:
    state: present
    name:
    - openldap
    - openldap-devel
    - openldap-servers
    - openldap-clients
  when: ansible_distribution == "Amazon"
