ARG GO_VERSION=latest
FROM easyrsa/local AS easyrsa
FROM golang:${GO_VERSION}
ARG PLM_BRANCH=main
ARG MAKE_TARGET=build
COPY --from=easyrsa /etc/x509/ca.crt /etc/pykmip/ca.crt
COPY --from=easyrsa /etc/x509/ /etc/x509/
RUN apt update && apt -y install curl socat git && \
    git clone https://github.com/percona/percona-link-mongodb.git && cd percona-link-mongodb && \
    git checkout $PLM_BRANCH && \
    n=0; until [ "$n" -ge 5 ]; do \
        make ${MAKE_TARGET} && break; \
        n=$((n+1)); echo "Retry $n/5 failed. Retrying in 5 seconds..."; \
        sleep 5; \
    done && \
    cp -rpf bin/* /usr/bin/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
