[tool.pytest.ini_options]
markers = [
    "plink_log_level(level): set plink log level for the test",
    "plink_env(env_vars): set plink environment variables for the test",
    "jenkins: mark test to run only in Jenkins or with --jenkins flag"
]
