- set_fact:
   psmdb_mongosh: "{{ psmdb_version.split('-')[1].split('.')[0] }}"

- name: install psmdb deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-server-mongodb
    - percona-server-mongodb-server
    - percona-server-mongodb-mongos
    - percona-server-mongodb-tools
    - percona-server-mongodb-dbg
  when: ansible_os_family == "Debian"

- name: install psmdb rpm packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - percona-server-mongodb
    - percona-server-mongodb-server
    - percona-server-mongodb-mongos
    - percona-server-mongodb-tools
    - percona-server-mongodb-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "7"

- name: install psmdb rpm packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - percona-server-mongodb
      - percona-server-mongodb-server
      - percona-server-mongodb-mongos
      - percona-server-mongodb-tools
      - percona-server-mongodb-debugsource
      - percona-server-mongodb-tools-debuginfo
      - percona-server-mongodb-mongos-debuginfo
      - percona-server-mongodb-server-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: install psmdb rpm packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - percona-server-mongodb
      - percona-server-mongodb-server
      - percona-server-mongodb-mongos
      - percona-server-mongodb-tools
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

- name: install mongo shell deb package
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - percona-server-mongodb-shell
  when: ansible_os_family == "Debian" and psmdb_mongosh < "6"

- name: install mongosh deb package
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - percona-mongodb-mongosh
  when: ansible_os_family == "Debian" and psmdb_mongosh >= "6"

- name: install mongo shell rpm package
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - percona-server-mongodb-shell
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "7" and psmdb_mongosh < "6"

- name: install mongo shell rpm packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - percona-server-mongodb-shell
      - percona-server-mongodb-shell-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8" and psmdb_mongosh < "6"

- name: install mongosh rpm package
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - percona-mongodb-mongosh
  when: ansible_os_family == "RedHat" and psmdb_mongosh >= "6"

- name: copy mongosh binary to mongo path for test scripts
  file:
    src: /usr/bin/mongosh
    dest: /usr/bin/mongo
    state: link
    force: true
  when: psmdb_mongosh >= "6"
