---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: al2023-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-0fa40e25bf4dda1f6
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: ${INSTANCE_TYPE:-t2.medium}
    ssh_user: ec2-user
    root_device_name: /dev/xvda
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
    s: true
    junitxml: al2023-report.xml
scenario:
  name: al2023
  converge_sequence:
    - prepare
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
