- name: Side effect
  hosts: mongo
  become: true
  become_method: sudo
  tasks:
    - name: get primary ip adrress
      set_fact:
        rs_primary_ip: "{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"
      when: inventory_hostname in groups['primary']

    - name: debug primary ip adress
      debug:
        msg: "{{rs_primary_ip}}"
      when: inventory_hostname in groups['primary']

    - name: get secondaries ip adresses
      set_fact:
        rs_secondary_ips: "{% for host in groups['secondary'] %}{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}{% if not loop.last %},{% endif %}{% endfor %}"

    - name: debug secondaries ip adresses
      debug:
        msg: "{{rs_secondary_ips}}"

    - name: stop mongod service
      service: name=mongod state=stopped

    - name: erase data directory for mongod
      shell: rm -rf /mnt/data/db/*

    - name: start mongod service
      service: name=mongod state=started

    - name: Create a replicaset rsnew
      community.mongodb.mongodb_replicaset:
        replica_set: rs
        login_host: "{{ rs_primary_ip }}"
        members:
        - host: "{{ rs_primary_ip }}:27017"
          priority: 1
        - host: "{{ rs_secondary_ips.split(',')[0] }}:27017"
          priority: 0.5
        - host: "{{ rs_secondary_ips.split(',')[1] }}:27017"
          priority: 0.5
      when: inventory_hostname in groups['primary']
