---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: unoble-pro-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-08c47e4b2806964ce
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: t3.large
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
    s: true
    junitxml: ubuntu-noble-pro-report.xml
scenario:
  name: ubuntu-noble-pro
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
