FROM easyrsa/local AS easyrsa

FROM python:3.11-alpine
USER root
RUN apk add --no-cache libffi-dev build-base bash git openssl && cd ~ && \
    pip install --upgrade --no-cache-dir --break-system-packages pip && \
    pip install --upgrade --no-cache-dir --break-system-packages "setuptools<80.0.0" && \
    pip install --no-cache-dir --break-system-packages pykmip && cd ~ && \
    git clone https://github.com/OpenKMIP/PyKMIP && \
    cd PyKMIP && \
    python setup.py install && \
    mkdir -p /etc/pykmip && \
    echo -e '\
    [server]\n\
    database_path=/etc/pykmip/pykmip.database\n\
    hostname=pykmip\n\
    port=5696\n\
    certificate_path=/etc/pykmip/pykmip.crt\n\
    key_path=/etc/pykmip/pykmip.key\n\
    ca_path=/etc/pykmip/ca.crt\n\
    auth_suite=TLS1.2\n\
    policy_path=/root/PyKMIP/examples/\n\
    enable_tls_client_auth=True\n\
    tls_cipher_suites= TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\n\
    logging_level=DEBUG\n\
    ' > /etc/pykmip/server.conf

COPY --from=easyrsa /etc/pykmip/ /etc/pykmip/

EXPOSE 5696
CMD /root/PyKMIP/bin/run_server.py
