version: "3"
services:
  test:
    build:
      dockerfile: ./Dockerfile-testinfra
      context: .
    volumes:
      - .:/test
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - fs:/backups
    container_name: test
    hostname: test
    networks:
      - test

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    networks:
      - test
    command: azurite-blob --blobHost 0.0.0.0

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - test
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups --console-address ":9001"

  createbucket:
    container_name: createbucket
    image: minio/mc
    networks:
      - test
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234; /usr/bin/mc mb myminio/bcp; exit 0; "

  pykmip:
    image: pykmip/local
    build:
      dockerfile: ./Dockerfile-pykmip
      context: .
    container_name: pykmip
    hostname: pykmip
    networks:
      - test

  vault:
    image: hashicorp/vault
    container_name: vault
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=vaulttoken"
    networks:
      - test

  build_member:
    image: replica_member/local
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - PBM_BRANCH=${PBM_BRANCH:-main}
        - GO_VER=${GO_VER:-latest}
        - PSMDB=${PSMDB:-percona/percona-server-mongodb:latest}
    command: /bin/bash
    depends_on:
      - pykmip

networks:
  test:
    name: test

volumes:
  backups: 
    name: backups
  fs: 
    name: fs
