version: "3"
services:
  test:
    build:
      dockerfile: ./Dockerfile-testinfra
      context: .
    volumes:
      - .:/test
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: test
    hostname: test
    networks:
      - test

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    networks:
      - test
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups

  createbucket:
    container_name: createbucket
    image: minio/mc
    networks:
      - test
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234; /usr/bin/mc mb myminio/bcp; exit 0; "

  build_member:
    image: replica_member/local
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - REPO=${REPO:-testing}
        - PBM_VERSION=${PBM_VERSION:-latest}
        - PSMDB_VERSION=${PSMDB_VERSION:-latest}
    command: /bin/bash

networks:
  test:
    name: test

volumes:
  backups: null
