version: "3"
services:
  newrs101:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs1 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs101
    hostname: newrs101

  newrs102:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs1 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs102
    hostname: newrs102

  newrs103:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs1 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs103
    hostname: newrs103

  newrs201:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs2 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs201
    hostname: newrs201

  newrs202:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs2 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs202
    hostname: newrs202

  newrs203:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrs2 --shardsvr --keyFile /etc/keyfile"
    container_name: newrs203
    hostname: newrs203

  newrscfg01:
    image: replica_member/local
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrscfg --configsvr --keyFile /etc/keyfile"
    container_name: newrscfg01
    hostname: newrscfg01

  newrscfg02:
    image: replica_member/local
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrscfg --configsvr --keyFile /etc/keyfile"
    container_name: newrscfg02
    hostname: newrscfg02

  newrscfg03:
    image: replica_member/local
    networks:
      - test
    environment:
      PBM_MONGODB_URI: "mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      MONGODB_EXTRA_ARGS: " --port 27017 --replSet newrscfg --configsvr --keyFile /etc/keyfile"
    container_name: newrscfg03
    hostname: newrscfg03

  newmongos:
    image: replica_member/local
    depends_on:
      - newrscfg01
      - newrscfg02
      - newrscfg03
    networks:
      - test
    command: "mongos --keyFile=/etc/keyfile --configdb newrscfg/newrscfg01:27017,newrscfg02:27017,newrscfg03:27017 --port 27017 --bind_ip 0.0.0.0"
    container_name: newmongos
    hostname: newmongos

networks:
  test:
    external: true
    name: test

