FROM alpine
RUN apk add --no-cache docker docker-compose python3 py-pip bash
RUN pip install --no-cache-dir docker && pip install --no-cache-dir pytest-testinfra && pip install --no-cache-dir pytest-docker-compose && pip install --no-cache-dir pymongo
WORKDIR /test
