- name: Install python2 packages
  yum:
    name: "{{packages}}"
    state: present
    disable_gpg_check: true
    validate_certs: false
  vars:
    packages:
    - git
    - python-pip
    - python-requests
    - python-sqlalchemy
    - python-cryptography
  when: ansible_distribution_major_version == "7"

- name: Install python3 packages
  yum:
    name: "{{packages}}"
    state: present
    disable_gpg_check: true
  vars:
    packages:
    - git
    - python3-pip
    - python3-sqlalchemy
  when: ansible_distribution_major_version|int >= 8

- name: Install python2 enum
  pip:
    name:
    - enum-compat==0.0.2
    executable: pip
    extra_args: "--trusted-host pypi.python.org"
  when: ansible_distribution_major_version == "7"

- name: Install python3 setuptools
  pip:
    name:
    - setuptools<71.0.0
    state: present
    executable: pip3
  when: ansible_distribution_major_version|int >= 8

- name: Debug python3 version RHEL8
  shell: "python3 --version"
  register: python_version
  when: ansible_distribution_major_version|int >= 8

- name: Display python version
  debug:
    var: python_version.stdout
  when: ansible_distribution_major_version|int >= 8

- name: Install python3 setuptools
  pip:
    name:
    - setuptools
    state: latest
    executable: pip3
  when: ansible_distribution_major_version == "8" and python_version.stdout.split(' ')[1] is version('3.8.0', '<')

- name: Install python3 setuptools
  pip:
    name:
    - setuptools<71.0.0
    state: present
    executable: pip3
  when: ansible_distribution_major_version == "8" and python_version.stdout.split(' ')[1] is version('3.8.0', '>')

- name: Add symlink for python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
    force: yes
  when: ansible_distribution_major_version|int >= 8
