  - name: Install pmm package Debian
    apt:
      name: pmm2-client
    when: ansible_os_family == "Debian"

  - name: Install pmm package RHEL
    yum:
      name: pmm2-client
    when: ansible_os_family == "RedHat"

  - set_fact:
      pmm_host: "{{ lookup('env', 'PMM_HOST') | default('none', true) }}"

  - name: Configure pmm
    command: "{{item}}"
    with_items:
      - pmm-admin config --server-insecure-tls --server-url={{ pmm_host }} --force
      - pmm-admin add mongodb
    when: pmm_host != "none" 
