- name: Create workdir
  file:
    path: /workdir
    state: directory
    mode: '0755'

- name: Download testing dir
  git:
    repo: 'https://github.com/Percona-QA/psmdb-testing.git'
    dest: /package-testing
    version: main

- name: Download test database
  get_url:
    url: https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json
    dest: /workdir/primer-dataset.json    
    mode: '0644'

- name: Download mongo driver
  get_url:
    url: https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.1/mongo-java-driver-3.12.1.jar
    dest: /workdir/mongo-java-driver.jar
    mode: '0644'

- name: Download sysbench test
  git:
    repo: 'https://github.com/Percona-Lab/sysbench-mongodb.git'
    dest: /workdir/sysbench-mongodb

- name: Download ycsb test
  get_url:
    url: 'https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-mongodb-binding-0.17.0.tar.gz'
    dest: /tmp/ycsb-mongodb-binding.tar.gz
    mode: '0644'    

- name: Unpack ycsb test
  unarchive:
    src: /tmp/ycsb-mongodb-binding.tar.gz
    dest: /workdir
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/ycsb-mongodb-binding,S'

- name: Download mgodatagen
  get_url:
    url: 'https://github.com/feliixx/mgodatagen/releases/download/v0.9.2/mgodatagen_0.9.2_Linux_x86_64.tar.gz'
    dest: /tmp/mgodatagen.tar.gz
    mode: '0644'

- name: Unpack mgodatagen
  unarchive:
    src: /tmp/mgodatagen.tar.gz
    dest: /workdir
    remote_src: yes

- name: Download mgodatagen test config
  get_url:
    url: 'https://raw.githubusercontent.com/feliixx/mgodatagen/master/datagen/testdata/big.json'
    dest: /workdir/big.json
    mode: '0644'

- name: Download mgodatagen test config for sharded cluster
  get_url:
    url: 'https://raw.githubusercontent.com/feliixx/mgodatagen/master/datagen/testdata/sharded_id.json'
    dest: /workdir/sharded_id.json
    mode: '0644'
