- name: install python2 for  debian11
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python2
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"

- name: install python2 for ubuntu 
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python2.7
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16"


- name: install python2 for RHEL8
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python2
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: reconfigure ycsb for using python2 when neccesary
  lineinfile:
    path: /workdir/ycsb-mongodb-binding/bin/ycsb
    regexp: '#!/usr/bin/env python'
    line: '#!/usr/bin/env python2'
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "11") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version == "8")

- name: reconfigure ycsb for using python2 when neccesary
  lineinfile:
    path: /workdir/ycsb-mongodb-binding/bin/ycsb
    regexp: '#!/usr/bin/env python'
    line: '#!/usr/bin/env python2.7'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16"

- name: create check file
  file:
    path: /python2_installed
    state: touch
    mode: 0644
