---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: include tasks for removing PSMDB
      include_tasks: ../../tasks/remove_psmdb.yml
      vars:
       psmdb_version: "{{ lookup('env', 'TO_PDMDB_VERSION') }}"
