---
- name: Side Effect
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: disable all repos
      command: percona-release disable all

    - name: enable new pdmdb repo
      command: percona-release enable {{ version }} {{ repo }}
      vars:
        repo: "{{ lookup('env', 'TO_REPO') }}"
        version: "{{ lookup('env', 'TO_PDMDB_VERSION') }}"

    - name: update psmdb deb packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-dbg
      when: ansible_os_family == "Debian"

    - name: update psmdb rpm packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-debugsource
        - percona-server-mongodb-shell-debuginfo
        - percona-server-mongodb-tools-debuginfo
        - percona-server-mongodb-mongos-debuginfo
        - percona-server-mongodb-server-debuginfo
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version == "8"

    - name: update psmdb rpm packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-debuginfo
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version <= "7"

    - name: restart mongod service
      service: 
        name: mongod
        state: restarted

    - name: update PBM deb packages
      apt:
        name: percona-backup-mongodb
        update_cache: yes
        state: latest
      when: ansible_os_family == "Debian"

    - name: update PBM rpm packages
      yum:
        name: percona-backup-mongodb
        state: latest
      when: ansible_os_family == "RedHat"

    - name: restart pbm-agent service
      service: 
        name: pbm-agent
        state: restarted
