ARG MONGODB_IMAGE=percona/percona-server-mongodb
FROM easyrsa/local AS easyrsa
FROM $MONGODB_IMAGE
COPY keyfile /etc/keyfile
COPY --from=easyrsa /etc/x509/ca.crt /etc/pykmip/ca.crt
COPY --from=easyrsa /etc/x509/ /etc/x509/
USER root
RUN mkdir -p /var/lib/mongo && \
    chown -R mongodb /var/lib/mongo && \
    chown mongodb /etc/keyfile && chmod 400 /etc/keyfile && \
    chown -R mongodb /etc/x509 && chmod 400 /etc/x509/*
ENTRYPOINT []
USER mongodb
