FROM python:3.11-alpine
RUN apk add --no-cache docker libffi-dev build-base bash git
RUN pip install --no-cache-dir --break-system-packages docker && \
    pip install --no-cache-dir --break-system-packages pytest-testinfra && \
    pip install --no-cache-dir --break-system-packages pytest-timeout && \
    pip install --no-cache-dir --break-system-packages pymongo && \
    pip install --no-cache-dir --break-system-packages debugpy
WORKDIR /test
