---
# tasks file for PSMDB
- set_fact:
    old_tarball: "{{ lookup('env', 'OLD_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-4.2/percona-server-mongodb-4.2.15-16/binary/tarball/percona-server-mongodb-4.2.15-16-x86_64.glibc2.17-minimal.tar.gz', true) }}"

- set_fact:
    layout_type: "{{ lookup('env', 'LAYOUT_TYPE') | default('single', true) }}"

- name: check correct layout type
  fail: 
    msg: incorrect layout type {{ layout_type }}
  when: layout_type != "single" and layout_type != "replicaset" and layout_type != "sharded" 

- set_fact:
    storage: "{{ lookup('env', 'STORAGE') | default('wiredTiger', true) }}"    

- name: check correct storage
  fail: 
    msg: incorrect storage type {{ storage }}
  when: storage != "wiredTiger" and storage != "inMemory"  

- set_fact:
    encryption: "{{ lookup('env', 'ENCRYPTION') | default('NONE', true) }}"
  when: storage == "wiredTiger"   

- name: check correct encryption
  fail:
    msg: incorrect encryption {{ encryption }}
  when: encryption != "NONE" and encryption != "VAULT" and encryption != "KEYFILE"

- set_fact:
    encryption: "NONE"
  when: storage == "inMemory"

- set_fact:
    cipher: "{{ lookup('env', 'CIPHER') | default('AES256-CBC', true) }}"

- set_fact:
    keyfile: "/package-testing/scripts/psmdb_encryption/mongodb-keyfile"

- set_fact:
    vault_token: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"

- set_fact:
    vault_cert: "/package-testing/scripts/psmdb_encryption/test.cer"

- set_fact:
    vault_secret: "secret_v2/data/psmdb-test/package-test"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --encryptionKeyFile {{ keyfile }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "KEYFILE"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --vaultServerName 127.0.0.1 --vaultPort 8200 --vaultTokenFile {{ vault_token }} --vaultSecret {{ vault_secret }} --vaultServerCAFile {{ vault_cert }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "VAULT"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --wiredTigerCacheSizeGB 0.25"
  when: encryption == "NONE" and storage == "wiredTiger"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --inMemorySizeGB 0.25"
  when: encryption == "NONE" and storage == "inMemory"
   
- name: Create data directories
  file:
    path: /usr/share/man/man1
    state: directory
    mode: 0775
   
- name: install necessary deb packages for ubuntu xenial
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl3
    - python3-pip 
    - python3-dev
    - python3-markdown
    - psmisc 
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: install necessary deb packages for ubuntu
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python3-pip
    - python3-dev
    - python3-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16"

- name: install necessary deb packages for debian 9
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl3
    - python-pip
    - python-dev
    - python-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- name: install necessary deb packages for debian 10
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python-pip
    - python-dev
    - python-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

- name: install necessary deb packages for debian 11
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python3-pip
    - python3-dev
    - python3-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"

- name: install necessary rpm packages for Centos7
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - curl
    - libcurl
    - python-pip
    - python-devel
    - python-markdown
    - psmisc
    - gcc
    - java
    - java-devel
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install necessary rpm packages for RHEL8
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - curl
    - python3-pip
    - python3-devel
    - python3-markdown
    - psmisc
    - gcc
    - java
    - java-devel
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Install necessary python package
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - pymongo 
    - subprocess32 
    - PyYAML 
    - typing 
    - requests 
    - Cheetah3 
    - regex 
    - awscli
    - boto
    - boto3
    - botocore

- name: Create workdir
  file:
    path: /workdir
    state: directory
    mode: '0755'

- name: Download new tarball
  get_url:
    url: '{{ old_tarball }}'
    dest: /tmp/percona-server-mongodb-old.tar.gz
    mode: '0644'

- name: Unpack new tarball
  unarchive: 
    src: /tmp/percona-server-mongodb-old.tar.gz
    dest: /                     
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/mongo-old-bindir,S'

- name: Download testing dir
  git:
    repo: 'https://github.com/Percona-QA/psmdb-testing.git'
    dest: /package-testing
    version: main

- name: Download test database
  get_url:
    url: https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json
    dest: /workdir/primer-dataset.json    
    mode: '0644'

- name: Download mongo driver
  get_url:
    url: https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.1/mongo-java-driver-3.12.1.jar
    dest: /workdir/mongo-java-driver.jar
    mode: '0644'

- name: Download sysbench test
  git:
    repo: 'https://github.com/Percona-Lab/sysbench-mongodb.git'
    dest: /workdir/sysbench-mongodb

- name: Download ycsb test
  get_url:
    url: 'https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-mongodb-binding-0.17.0.tar.gz'
    dest: /tmp/ycsb-mongodb-binding.tar.gz
    mode: '0644'    

- name: Unpack ycsb test
  unarchive:
    src: /tmp/ycsb-mongodb-binding.tar.gz
    dest: /workdir
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/ycsb-mongodb-binding,S'

- name: Download mgodatagen
  get_url:
    url: 'https://github.com/feliixx/mgodatagen/releases/download/v0.9.2/mgodatagen_0.9.2_Linux_x86_64.tar.gz'
    dest: /tmp/mgodatagen.tar.gz
    mode: '0644'

- name: Unpack mgodatagen
  unarchive:
    src: /tmp/mgodatagen.tar.gz
    dest: /workdir
    remote_src: yes

- name: Install and configure vault
  include_tasks: ../../../tasks/install_and_configure_vault.yml
  when: encryption == "VAULT"

- name: Ensure keyfile has correct permissions
  file:
    path: "{{ keyfile }}"
    mode: '0400'
  when: encryption == "KEYFILE"

- name: Ensure vault_cert has correct permissions
  file:
    path: "{{ vault_token }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Ensure vault_token has correct permissions
  file:
    path: "{{ vault_cert }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - /workdir/single
    - /workdir/rs0-1
    - /workdir/rs0-2
    - /workdir/rs0-3
    - /workdir/rs1-1
    - /workdir/rs1-2
    - /workdir/rs1-3
    - /workdir/cfg1-1
    - /workdir/cfg1-2
    - /workdir/cfg1-3

- name: Start single mongo
  command: /mongo-new-bindir/bin/mongod --fork --syslog --dbpath /workdir/single {{ mongo_opts }}
  when: layout_type == "single"

- name: Start replicaset
  command: "{{ item }}"
  with_items:    
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-1 --port 27017 --replSet rs0 {{ mongo_opts }}   
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-2 --port 27018 --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-3 --port 27019 --replSet rs0 {{ mongo_opts }}
  when: layout_type == "replicaset" 

- name: Create a replicaset rs0
  community.mongodb.mongodb_replicaset:
    replica_set: rs0
    members:
    - host: "localhost:27017"
      priority: 1
    - host: "localhost:27018"
      priority: 0.5
    - host: "localhost:27019"
      priority: 0.5
  when: layout_type == "replicaset"

- name: Start sharded
  command: "{{ item }}"
  with_items:
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-1 --port 28017 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-2 --port 28018 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-3 --port 28019 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-1 --port 29017 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-2 --port 29018 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-3 --port 29019 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-1 --port 30017 --configsvr --replSet cfg {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-2 --port 30018 --configsvr --replSet cfg {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-3 --port 30019 --configsvr --replSet cfg {{ mongo_opts }}
  when: layout_type == "sharded"

- name: Create a replicaset rs0
  community.mongodb.mongodb_replicaset:
    login_port: 28017
    replica_set: rs0
    members:
    - host: "localhost:28017"
      priority: 1
    - host: "localhost:28018"
      priority: 0.5
    - host: "localhost:28019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Create a replicaset rs1
  community.mongodb.mongodb_replicaset:
    login_port: 29017
    replica_set: rs1
    members:
    - host: "localhost:29017"
      priority: 1
    - host: "localhost:29018"
      priority: 0.5
    - host: "localhost:29019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Create a replicaset cfg
  community.mongodb.mongodb_replicaset:
    login_port: 30017
    replica_set: cfg
    members:
    - host: "localhost:30017"
      priority: 1
    - host: "localhost:30018"
      priority: 0.5
    - host: "localhost:30019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Start mongos
  command: /mongo-old-bindir/bin/mongos --fork --syslog --configdb cfg/localhost:30017,localhost:30018,localhost:30019 --port 27017 --bind_ip 0.0.0.0
  when: layout_type == "sharded"

- name: Init sharded
  command: "{{item}}"
  with_items:
    - /mongo-old-bindir/bin/mongo --eval 'sh.addShard( "rs0/localhost:28017,localhost:28018,localhost:28019" )'
    - /mongo-old-bindir/bin/mongo --eval 'sh.addShard( "rs1/localhost:29017,localhost:29018,localhost:29019" )'
  when: layout_type == "sharded"
