---
# tasks file for PSMDB
- set_fact:
    old_tarball: "{{ lookup('env', 'OLD_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-4.2/percona-server-mongodb-4.2.15-16/binary/tarball/percona-server-mongodb-4.2.15-16-x86_64.glibc2.17-minimal.tar.gz', true) }}"

- set_fact:
    new_tarball: "{{ lookup('env', 'NEW_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-LATEST/percona-server-mongodb-4.4.8-9/binary/tarball/percona-server-mongodb-4.4.8-9-x86_64.glibc2.17-minimal.tar.gz', true) }}"

- name: get mongodb old version
  set_fact:
    mongodb_old_ver: "{{ old_tarball | regex_search('mongodb-([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') }}"

- name: get mongodb new version
  set_fact:
    mongodb_new_ver: "{{ new_tarball | regex_search('mongodb-([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') }}"

- set_fact:
    layout_type: "{{ lookup('env', 'LAYOUT_TYPE') | default('single', true) }}"

- set_fact:
    storage: "{{ lookup('env', 'STORAGE') | default('wiredTiger', true) }}"    

- set_fact:
    encryption: "{{ lookup('env', 'ENCRYPTION') | default('NONE', true) }}"
  when: storage == "wiredTiger"   

- set_fact:
    cipher: "{{ lookup('env', 'CIPHER') | default('AES256-CBC', true) }}"

- set_fact:
    encryption: "NONE"
  when: storage == "inMemory"

- set_fact:
    keyfile: "/package-testing/scripts/psmdb_encryption/mongodb-keyfile"

- set_fact:
    vault_token: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"

- set_fact:
    vault_cert: "/package-testing/scripts/psmdb_encryption/test.cer"

- set_fact:
    vault_secret: "secret_v2/data/psmdb-test/package-test"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --encryptionKeyFile {{ keyfile }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "KEYFILE"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --vaultServerName 127.0.0.1 --vaultPort 8200 --vaultTokenFile {{ vault_token }} --vaultSecret {{ vault_secret }} --vaultServerCAFile {{ vault_cert }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "VAULT"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --wiredTigerCacheSizeGB 0.25"
  when: encryption == "NONE" and storage == "wiredTiger"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --inMemorySizeGB 0.25"
  when: encryption == "NONE" and storage == "inMemory"

- name: check if packages installed
  stat:
    path: /pkgs_installed
  register: pkgs_installed
   
- name: Install neccesary software for different OS
  include_tasks: ../../../tasks/install_soft_for_tarball_tests.yml
  when: not pkgs_installed.stat.exists

- name: Check that testing directory exists
  stat:
    path: /package-testing
  register: testing_dir

- name: Download tests
  include_tasks: ../../../tasks/install_tests_for_tarball.yml
  when: not testing_dir.stat.exists

- name: check if python2 installed
  stat:
    path: /python2_installed
  register: python2_installed

- name: Install neccesary software for different OS
  include_tasks: ../../../tasks/install_soft_for_ycsb_tests.yml
  when: not python2_installed.stat.exists

- name: Check that the vault_token exists
  stat:
    path: "{{ vault_token }}"
  register: vault_exists

- name: Install and configure vault
  include_tasks: ../../../tasks/install_and_configure_vault.yml
  when: encryption == "VAULT" and not vault_exists.stat.exists

- name: Check that bin directory exists
  stat:
    path: /mongo-old-bindir
  register: mongo_dir

- name: Copy tarball
  copy:
    src: /tmp/percona-server-mongodb-old-{{mongodb_old_ver[0]}}.tar.gz
    dest: /tmp/percona-server-mongodb-old.tar.gz
    mode: '0644'
  when: not mongo_dir.stat.exists

- name: Unpack old tarball
  unarchive: 
    src: /tmp/percona-server-mongodb-old.tar.gz
    dest: /                     
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/mongo-old-bindir,S'
  when: not mongo_dir.stat.exists

- name: Ensure keyfile has correct permissions
  file:
    path: "{{ keyfile }}"
    mode: '0400'
  when: encryption == "KEYFILE"

- name: Ensure vault_cert has correct permissions
  file:
    path: "{{ vault_token }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Ensure vault_token has correct permissions
  file:
    path: "{{ vault_cert }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - /workdir/single
    - /workdir/rs0-1
    - /workdir/rs0-2
    - /workdir/rs0-3
    - /workdir/rs1-1
    - /workdir/rs1-2
    - /workdir/rs1-3
    - /workdir/cfg1-1
    - /workdir/cfg1-2
    - /workdir/cfg1-3

- name: Start single mongo
  command: /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/single --port 27017 {{ mongo_opts }}
  when: layout_type == "single"

- name: Start replicaset
  command: "{{ item }}"
  with_items:    
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-1 --port 27017 --replSet rs0 {{ mongo_opts }}   
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-2 --port 27018 --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-3 --port 27019 --replSet rs0 {{ mongo_opts }}
  when: layout_type == "replicaset" 

- name: Create a replicaset rs0
  community.mongodb.mongodb_replicaset:
    replica_set: rs0
    members:
    - host: "localhost:27017"
      priority: 1
    - host: "localhost:27018"
      priority: 0.5
    - host: "localhost:27019"
      priority: 0.5
  when: layout_type == "replicaset"

- name: Ensure replicaset is stable
  community.mongodb.mongodb_status:
    replica_set: rs0
    poll: 3
    interval: 10
  when: layout_type == "replicaset"

- name: Start sharded
  command: "{{ item }}"
  with_items:
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-1 --port 28017 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-2 --port 28018 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs0-3 --port 28019 --shardsvr --replSet rs0 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-1 --port 29017 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-2 --port 29018 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/rs1-3 --port 29019 --shardsvr --replSet rs1 {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-1 --port 30017 --configsvr --replSet cfg {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-2 --port 30018 --configsvr --replSet cfg {{ mongo_opts }}
    - /mongo-old-bindir/bin/mongod --fork --syslog --dbpath /workdir/cfg1-3 --port 30019 --configsvr --replSet cfg {{ mongo_opts }}
  when: layout_type == "sharded"

- name: Create a replicaset rs0
  community.mongodb.mongodb_replicaset:
    login_port: 28017
    replica_set: rs0
    members:
    - host: "localhost:28017"
      priority: 1
    - host: "localhost:28018"
      priority: 0.5
    - host: "localhost:28019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Ensure replicaset is stable
  community.mongodb.mongodb_status:
    replica_set: rs0
    login_port: 28017
    poll: 3
    interval: 10
  when: layout_type == "sharded"

- name: Create a replicaset rs1
  community.mongodb.mongodb_replicaset:
    login_port: 29017
    replica_set: rs1
    members:
    - host: "localhost:29017"
      priority: 1
    - host: "localhost:29018"
      priority: 0.5
    - host: "localhost:29019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Ensure replicaset is stable
  community.mongodb.mongodb_status:
    replica_set: rs1
    login_port: 29017
    poll: 3
    interval: 10
  when: layout_type == "sharded"

- name: Create a replicaset cfg
  community.mongodb.mongodb_replicaset:
    login_port: 30017
    replica_set: cfg
    members:
    - host: "localhost:30017"
      priority: 1
    - host: "localhost:30018"
      priority: 0.5
    - host: "localhost:30019"
      priority: 0.5
  when: layout_type == "sharded"

- name: Ensure replicaset is stable
  community.mongodb.mongodb_status:
    replica_set: cfg
    login_port: 30017
    poll: 3
    interval: 10
  when: layout_type == "sharded"

- name: Start mongos
  command: /mongo-old-bindir/bin/mongos --fork --syslog --configdb cfg/localhost:30017,localhost:30018,localhost:30019 --port 27017 --bind_ip 0.0.0.0
  when: layout_type == "sharded"

- name: Init sharded
  command: "{{item}}"
  with_items:
    - /mongo-old-bindir/bin/mongo --eval 'sh.addShard( "rs0/localhost:28017,localhost:28018,localhost:28019" )'
    - /mongo-old-bindir/bin/mongo --eval 'sh.addShard( "rs1/localhost:29017,localhost:29018,localhost:29019" )'
  when: layout_type == "sharded"

- name: Generate test data for single
  command: /workdir/mgodatagen -f /workdir/big.json
  register: datagen
  when: layout_type == "single"

- set_fact: mgodatagen="{{datagen.stdout_lines}}"
  when: datagen.changed

- name: Generate test data for replicaset
  command: /workdir/mgodatagen --uri=mongodb://127.0.0.1/?replicaSet=rs0 -f /workdir/big.json
  register: datagen
  when: layout_type == "replicaset"

- set_fact: mgodatagen="{{datagen.stdout_lines}}"
  when: datagen.changed

- name: Generate test data for sharded
  command: /workdir/mgodatagen -f /workdir/sharded_id.json
  register: datagen
  when: layout_type == "sharded"

- set_fact: mgodatagen="{{datagen.stdout_lines}}"
  when: datagen.changed

- name: debug mgodatagen result         
  debug:
    msg: "{{mgodatagen}}"

- name: Generate ycsb data for single or sharded
  command: /workdir/ycsb-mongodb-binding/bin/ycsb load mongodb -s -P /workdir/ycsb-mongodb-binding/workloads/workloadb -p recordcount=100000 -p mongodb.auth="false"
  register: ycsb_load
  when: layout_type == "single" or layout_type == "sharded"

- set_fact: ycsb="{{ycsb_load.stdout_lines}}"
  when: ycsb_load.changed

- name: Generate ycsb data for replicaset
  command: /workdir/ycsb-mongodb-binding/bin/ycsb load mongodb -s -P /workdir/ycsb-mongodb-binding/workloads/workloadb  -p recordcount=100000 -p mongodb.url="mongodb://localhost:27017/ycsb?replicaSet=rs0&w=1" -p mongodb.auth="false"
  register: ycsb_load
  when: layout_type == "replicaset"

- set_fact: ycsb="{{ycsb_load.stdout_lines}}"
  when: ycsb_load.changed

- name: debug ycsb result
  debug:
    msg: "{{ycsb}}"
