FROM alpine
USER root
ENV EASYRSA_DN=org
ENV EASYRSA_REQ_COUNTRY=US
ENV EASYRSA_REQ_PROVINCE=California
ENV EASYRSA_REQ_CITY=SanFrancisco
ENV EASYRSA_REQ_ORG=Percona
ENV EASYRSA_REQ_EMAIL=pcsm@percona.com
RUN apk add --no-cache bash git openssl && cd ~ && \
    git clone https://github.com/OpenVPN/easy-rsa.git && \
    cd easy-rsa/easyrsa3/ && \
    ./easyrsa init-pki && \
    ./easyrsa --req-cn=Percona --batch --days=365 build-ca nopass
WORKDIR /root/easy-rsa/easyrsa3
RUN ./easyrsa --req-ou=server --days=90 --subject-alt-name=DNS:localhost,DNS:rs101,DNS:rs201,DNS:mongos1,DNS:mongos2,IP:127.0.0.1 --batch build-server-full psmdb nopass && \
    ./easyrsa --req-ou=client --days=90 --batch build-client-full pcsm nopass && \
    mkdir -p /etc/x509 && \
    cp pki/ca.crt /etc/x509/ && \
    cat pki/issued/psmdb.crt pki/private/psmdb.key > /etc/x509/psmdb.pem && \
    cat pki/issued/pcsm.crt pki/private/pcsm.key > /etc/x509/pcsm.pem
