---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: jenkins-pml-source
    groups:
      - psmdb
    region: us-west-2
    image: "${MOLECULE_UNOBLE_AMI:-ami-0ea4e9f7a6f7c30c8}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
  - name: jenkins-pml-destination
    groups:
      - psmdb
    region: us-west-2
    image: "${MOLECULE_UNOBLE_AMI:-ami-0ea4e9f7a6f7c30c8}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
  - name: jenkins-pml-mongolink
    region: us-west-2
    image: "${MOLECULE_UNOBLE_AMI:-ami-0ea4e9f7a6f7c30c8}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../../../../playbooks/create.yml
    prepare: ../../../playbooks/prepare.yml
    converge: ../../../playbooks/converge.yml
    cleanup: ../../../playbooks/cleanup.yml
    destroy: ../../../../playbooks/destroy.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: aws
  test_sequence:
    - create
#    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
