- name: Install Dependencies (AL2023)
  become: true
  package:
    name:
      - python3-pip
    state: present
  when: ansible_facts.os_family == 'Amazon'

- name: Create Python virtualenv for Ansible deps
  become: true
  command: python3 -m venv /opt/ansible-venv
  when: ansible_facts.os_family == 'Amazon'

- name: Install Python deps into the venv
  become: true
  command: pip install docker requests
  when: ansible_facts.os_family == 'Amazon'