- name: Create Python virtualenv
  command: python3 -m venv /opt/ansible-venv
  when: ansible_facts.distribution | lower == 'amazon'

- name: Install dependencies
  command: pip install docker requests
  when: ansible_facts.distribution | lower == 'amazon'