- name: Install Pip (AL2023)
  package:
    name:
      - python3-pip
    state: present
  when: ansible_facts.distribution | lower == 'amazon'

- name: Upgrade pip inside venv (AL2023)
  command: /opt/ansible-venv/bin/pip install --upgrade pip
  when: ansible_facts.distribution | lower == 'amazon'

- name: Install deps inside venv (AL2023)
  command: /opt/ansible-venv/bin/pip install --upgrade --ignore-installed docker requests
  when: ansible_facts.distribution | lower == 'amazon'