- name: Install Python deps via apt (Debian)
  apt:
    update_cache: yes
    name:
      - python3-requests
      - python3-docker
    state: present
  become: yes
  when: ansible_os_family == "Debian"
