---
- name: Download packages to localhost
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get mongodb version
      set_fact:
        full_ver: "{{ lookup('env', 'PSMDB_VERSION') }}"

    - name: Get mongodb major version
      set_fact:
        maj_version: "{{ full_ver[0].split('.')[0] }}"
        minor_version: "{{ full_ver.split('-')[0] }}"

    - name: Debug mongodb major version
      debug:
        msg: "{{ maj_version }}"

    - set_fact:
        tarball_ol9: "https://repo.percona.com/private/{{ id }}-{{ token }}/qa-test/psmdb-gated-{{ minor_version }}/percona-server-mongodb-pro-{{ full_ver }}-x86_64.ol9.tar.gz"
      vars:
        id: "{{ lookup('env', 'USERNAME') }}"
        token: "{{ lookup('env', 'PASSWORD') }}"

    - set_fact:
        tarballs:
          - { original: 'ol9', replacement: 'ol9', var_name: 'tarball_ol9' }
          - { original: 'ol9', replacement: 'ol8', var_name: 'tarball_ol8' }
          - { original: 'ol9', replacement: 'ol2023', var_name: 'tarball_ol2023' }
          - { original: 'ol9', replacement: 'jammy', var_name: 'tarball_jammy' }
          - { original: 'ol9', replacement: 'noble', var_name: 'tarball_noble' }

    - set_fact:
        tarballs: "{{ tarballs + [{'original': 'ol9', 'replacement': 'bookworm', 'var_name': 'tarball_deb12'}] }}"
      when: maj_version > '6'

    - name: Set dynamic tarball links based on replacements
      set_fact:
        "{{ item.var_name }}": "{{ tarball_ol9 | regex_replace(item.original, item.replacement) }}"
      loop: "{{ tarballs }}"
      loop_control:
        loop_var: item

    - name: Download tarballs based on dynamically created URLs
      get_url:
        url: "{{ lookup('vars', item.var_name) }}"
        dest: /tmp/
        mode: '0644'
      ignore_errors: yes
      loop: "{{ tarballs }}"
      loop_control:
        loop_var: item

- name: Converge
  hosts: all
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - role: psmdb-tarball-pro
    - role: '../../../roles/docker'
    - role: '../../../roles/openldap'
    - role: '../../../roles/kerberos'
    - role: '../../../roles/kmip'
    - role: '../../../roles/vault'
