---
- name: Side Effect
  hosts: all
  vars:
    to_repo: "{{ lookup('env', 'TO_REPO') }}"
    from_repo: "{{ lookup('env', 'FROM_REPO') }}"
    to_version: "{{ lookup('env', 'TO_PSMDB_VERSION') }}"
    from_version: "{{ lookup('env', 'FROM_PSMDB_VERSION') }}"
  become: true
  become_method: sudo
  tasks:
    - name: set compatibilty version for downgrade
      shell: |
        mongo --quiet --eval 'db.adminCommand({setFeatureCompatibilityVersion: "{{compatibilty_version}}" })'
      register: set_version
      vars:
        compatibilty_version: "{{ to_version.split('.')[0] }}.{{ to_version.split('.')[1] }}"
      when: from_version > to_version
    
    - name: debug output
      debug:
        var: set_version

    - name: stop services for downgrade
      service:
        name: mongod
        state: stopped  
      when: from_version > to_version

    - name: install necessary deb packages for downgrade
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
      vars:
        packages:
        - dialog
        - apt-utils
      when: ansible_os_family == "Debian" and from_version > to_version

    - name: uninstall psmdb deb packages for downgrade
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: absent
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-dbg
      when: ansible_os_family == "Debian" and from_version > to_version 

    - name: uninstall psmdb rpm packages for downgrade
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: absent
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-debugsource
        - percona-server-mongodb-shell-debuginfo
        - percona-server-mongodb-tools-debuginfo
        - percona-server-mongodb-mongos-debuginfo
        - percona-server-mongodb-server-debuginfo
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version == "8" and from_version > to_version

    - name: uninstall psmdb rpm packages for downgrade
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: absent
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-shell
        - percona-server-mongodb-tools
        - percona-server-mongodb-debuginfo
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version <= "7" and from_version > to_version

    - name: disable all repos
      command: percona-release disable all

    - name: enable new psmdb repo
      command: percona-release enable psmdb-{{ to_version.split('.')[0] }}{{ to_version.split('.')[0] }} {{ to_repo }}

    - name: update psmdb deb packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - percona-server-mongodb={{ to_version }}*
        - percona-server-mongodb-server={{ to_version }}*
        - percona-server-mongodb-mongos={{ to_version }}*
        - percona-server-mongodb-shell={{ to_version }}*
        - percona-server-mongodb-tools={{ to_version }}*
        - percona-server-mongodb-dbg={{ to_version }}*
      when: ansible_os_family == "Debian"

    - name: update psmdb rpm packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb-{{ to_version }}
        - percona-server-mongodb-server-{{ to_version }}
        - percona-server-mongodb-mongos-{{ to_version }}
        - percona-server-mongodb-shell-{{ to_version }}
        - percona-server-mongodb-tools-{{ to_version }}
        - percona-server-mongodb-debugsource-{{ to_version }}
        - percona-server-mongodb-shell-debuginfo-{{ to_version }}
        - percona-server-mongodb-tools-debuginfo-{{ to_version }}
        - percona-server-mongodb-mongos-debuginfo-{{ to_version }}
        - percona-server-mongodb-server-debuginfo-{{ to_version }}
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version == "8"

    - name: update psmdb rpm packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb-{{ to_version }}
        - percona-server-mongodb-server-{{ to_version }}
        - percona-server-mongodb-mongos-{{ to_version }}
        - percona-server-mongodb-shell-{{ to_version }}
        - percona-server-mongodb-tools-{{ to_version }}
        - percona-server-mongodb-debuginfo-{{ to_version }}
      when: ansible_os_family == "RedHat"  and ansible_distribution_major_version <= "7"

    - name: perform daemon-reload for systemd-based os
      systemd:
        daemon_reload: yes
      when: ansible_service_mgr == "systemd"

    - name: change permissions to mongodb directory
      file:
        path: /var/lib/mongo
        state: directory
        recurse: yes
        owner: mongod
        group: mongod

    - name: restart mongod service
      service: 
        name: mongod
        state: restarted

