---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel8-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: "${MOLECULE_RHEL8_AMI:-ami-087c2c50437d0b80d}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    prepare: ../../playbooks/prepare.yml
    destroy: ../../../../playbooks/destroy.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: rhel8
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
