---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - set_fact:
        # Version of psmdb release to be enabled (psmdb-70)
        psmdb_to_test: "{{ lookup('env', 'PSMDB') | default('psmdb-80', true) }}"

    - set_fact:
        # Github token to access mongolink repo
        token: "{{ lookup('env', 'MONGO_REPO_TOKEN') }}"

    - set_fact:
        # Version of psmdb (e.g. 7.0.16)
        psmdb_version: "{{ lookup('env', 'PSMDB_VERSION') | default('latest', true) }}"

    - set_fact:
        # Version of mongosh
        psmdb_mongosh: "{{ psmdb_to_test.split('-')[1].split('.')[0] }}"

    - set_fact:
        # Branch of pml branch to test
        pml_branch: "{{ lookup('env', 'PML_BRANCH') | default('main', true) }}"

    - set_fact:
        # Go Version
        golang_version: "{{ lookup('env', 'GO_VERSION') | default('1.24.2', true) }}"

    - set_fact:
        # User to log into each AWS Instance
        ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

    - name: Change Node hostname
      hostname:
        name: pml-source
      when: inventory_hostname == "pml-package-test"

    - name: Prerequisite for debian 11
      apt:
        name: iproute2
        update_cache: yes
      when: ansible_distribution == "Debian" and ansible_distribution_major_version >= "11"

    - name: Install deps
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - jq
          - vim
          - zlib-devel
          - libjpeg-devel
          - freetype-devel
          - gcc
          - python3-devel
          - python3.12
          - python3-pip
          - make
          - wget
          - git
      when: ansible_os_family == "RedHat"

    - name: Install deps
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - jq
          - vim
          - zlib1g-dev
          - libjpeg-dev
          - libfreetype6-dev
          - gcc
          - python3-dev
          - python3.12
          - python3-pip
          - make
          - wget
          - git
          - iputils-ping
      when: ansible_os_family == "Debian"

    - name: Remove podman-docker if present
      ansible.builtin.yum:
        name: podman-docker
        state: absent

    - name: Install dnf plugins (for managing repos)
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: Add Docker CE repository
      ansible.builtin.command: >
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE and dependencies
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Download runc binary
      get_url:
        url: https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
        dest: /usr/local/bin/runc
        mode: '0755'

    - name: Move runc to /usr/bin
      copy:
        src: /usr/local/bin/runc
        dest: /usr/bin/runc
        remote_src: yes
        mode: '0755'
        force: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user ssh-user to docker group
      user:
        name: "{{ ssh_user }}"
        groups: docker
        append: yes

    - name: Create Source standalone PSMDB container
      community.docker.docker_container:
        name: source
        image: percona/percona-server-mongodb:8.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "27017:27017"
        command: "--port=27017"

    - name: Create Destination standalone PSMDB container
      community.docker.docker_container:
        name: destination
        image: percona/percona-server-mongodb:8.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "28017:27017"
        command: "--port=27017"

    - name: Get info about the container
      community.docker.docker_container_info:
        name: source
      register: source_container

    - name: Get info about the container
      community.docker.docker_container_info:
        name: destination
      register: destination_container

    - name: Store the Source Container IP
      set_fact:
        source_ip: "{{ source_container.container.NetworkSettings.Networks.bridge.IPAddress }}"

    - name: Store the Destination Container IP
      set_fact:
        destination_ip: "{{ destination_container.container.NetworkSettings.Networks.bridge.IPAddress }}"

    - name: Add container IPs to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present
        create: yes
      loop:
        - { ip: "{{ source_ip }}", hostname: "source" }
        - { ip: "{{ destination_ip }}", hostname: "destination" }
      become: true

    - name: Install Go from official tarball on PML host
      vars:
        go_version: "{{ golang_version }}"
        go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
        go_url: "https://go.dev/dl/{{ go_tarball }}"
        go_install_dir: "/usr/local"
      block:
        - name: Download Go {{ go_version }}
          get_url:
            url: "{{ go_url }}"
            dest: "/tmp/{{ go_tarball }}"
            mode: '0644'

        - name: Extract Go
          unarchive:
            src: "/tmp/{{ go_tarball }}"
            dest: "{{ go_install_dir }}"
            remote_src: yes

    - name: Check Go is available
      command: go version
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      register: go_version_output
      ignore_errors: true

    - name: Install Pymongo for Redhat
      pip:
        name:
          - pymongo
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install Pymongo on Debian
      command: python3 -m pip install --break-system-packages pymongo
      when: ansible_facts['os_family'] == 'Debian'

    - name: Clone PML repo
      timeout: 180
      git:
        repo: 'https://{{ token }}@github.com/Percona-Lab/percona-mongolink.git'
        dest: /tmp/percona-mongolink
        version: "{{ pml_branch }}"

    - name: Build PML
      command: make build
      args:
        chdir: /tmp/percona-mongolink
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOROOT: /usr/local/go/
        GOBIN: /usr/local/go/bin

    - name: Move mongolink binary to /usr/local/bin
      copy:
        src: /tmp/percona-mongolink/bin/percona-mongolink
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: true

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Create PML system unit file with optional environment variables
      copy:
        dest: /etc/systemd/system/pml.service
        content: |
          [Unit]
          Description=Percona MongoLink Service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/percona-mongolink \
            --source mongodb://{{ source_ip }}:27017 \
            --target mongodb://{{ destination_ip }}:27017 \
            --log-level debug \
            --log-json
          Restart=on-failure
          User=root

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd and start PML service
      service:
        daemon_reload: yes
        name: pml.service
        state: started