---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: source
    groups:
      - psmdb
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    networks:
      - name: test
  - name: destination
    groups:
      - psmdb
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    networks:
       - name: test
  - name: pml
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    networks:
      - name: test
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../../replicaset/playbooks/converge.yml
    cleanup: ../../../replicaset/playbooks/cleanup.yml
    side_effect: ../../../replicaset/playbooks/side-effect.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
#    capture: sys
#    o: junit_logging=system-out
    s: true
    junitxml: report.xml
scenario:
  name: docker
  test_sequence:
    - create
    - converge
    - verify
    - cleanup
    - destroy
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
