---
- name: Side Effect
  hosts: all
  become: true
  become_method: sudo
  vars:
    RPM_PACKAGE: "percona-backup-mongodb-{{ lookup('env', 'VERSION') }}"
    DEB_PACKAGE: "percona-backup-mongodb={{ lookup('env', 'VERSION') }}*"
  tasks:
    - name: Stop pbm-agent service
      service:
        name: pbm-agent
        state: stopped

    - name: Install new PBM version (APT)
      apt:
        name: "{{ DEB_PACKAGE }}"
        update_cache: yes
        force: yes
      when: ansible_os_family == "Debian"

    - name: Install new PBM version (YUM)
      yum:
        name: "{{ RPM_PACKAGE }}"
        allow_downgrade: yes
      when: ansible_os_family == "RedHat"

    - name: perform daemon-reload for systemd-based os
      systemd:
        daemon_reload: yes
      when: ansible_service_mgr == "systemd"

    - name: Start pbm-agent service
      service:
        name: pbm-agent
        state: started
        enabled: yes
