---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: primary-rs
    groups:
      - mongo
      - primary
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    networks:
      - name: test
  - name: secondary1-rs
    groups:
      - mongo
      - secondary
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    networks:
       - name: test
  - name: secondary2-rs
    groups:
      - mongo
      - secondary
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    networks:
      - name: test
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../playbooks/converge.yml
    cleanup: ../../playbooks/cleanup.yml
    side_effect: ../../playbooks/side-effect.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
#    capture: sys
#    o: junit_logging=system-out
    s: true
    junitxml: report.xml
scenario:
  name: docker
  test_sequence:
    - create
    - converge
    - verify
    - cleanup
    - destroy
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
