#- name: Include OS-specific tasks
#  include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure Python dependencies for Docker modules are installed
  ansible.builtin.pip:
    name:
      - docker
      - requests

- name: Ensure Docker network exists
  community.docker.docker_network:
    name: test
    driver: bridge
    state: present

- name: Run OpenLDAP container
  docker_container:
    name: ldap
    image: bitnamilegacy/openldap:latest
    restart_policy: unless-stopped
    hostname: ldap
    published_ports:
      - "1389:1389"
      - "1636:1636"
    env:
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_USERS: "pbm"
      LDAP_PASSWORDS: "pbmpass"
    networks:
      - name: test