---
- include_vars: all.yml
- include_vars: "Debian-vars.yml"

- name: Ensure Docker network exists
  community.docker.docker_network:
    name: test
    driver: bridge
    state: present

- name: Remove any existing container
  community.docker.docker_container:
    name: ldap
    state: absent
    keep_volumes: false

- name: Copy entire ldif directory to host
  ansible.builtin.copy:
    src: templates
    dest: /tmp/ldifs/
    mode: "0644"
    directory_mode: "0755"

- name: Run OpenLDAP container
  docker_container:
    name: ldap
    image: bitnamilegacy/openldap:latest
    restart_policy: unless-stopped
    hostname: ldap
    published_ports:
      - "389:1389"
      - "1636:1636"
    env:
      LDAP_ROOT: "dc=percona,dc=com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "secret"
      LDAP_SKIP_DEFAULT_TREE: "yes"
      LDAP_CUSTOM_LDIF_DIR: /tmp/ldifs/templates
    volumes: /tmp/ldifs:/tmp/ldifs:ro
    networks:
      - name: test
