- name: Prepare
  hosts: mongo
  become: true
  become_method: sudo
  tasks:
    - name: Get list of block devices
      command: 'lsblk -lno NAME'
      register: results

    - name: Create variable block_devices
      set_fact:
        block_devices: "{{ results.stdout_lines }}"

    - debug:
        var: block_devices

    - name: Create File System
      filesystem:
        fstype: xfs
        dev: "/dev/nvme0n1"

    - name: Create and mount disks
      mount:
        path: "/mnt/data"
        src: "/dev/nvme0n1"
        fstype: xfs
        opts: defaults,noatime,nodiscard
        state: mounted

    - set_fact:
        ssh_pubkey: "{{ lookup('env', 'SSH_PUBKEY') | default('none', true) }}"

    - set_fact:
        ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

    - name: Add user
      user:
        name: "{{ ssh_user }}"
        shell: /bin/bash
        groups: wheel
        append: yes
      when: ssh_user != "none" and ssh_pubkey != "none"

    - name: Add pub key
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ ssh_pubkey }}"
      when: ssh_user != "none" and ssh_pubkey != "none"
