- name: Add HashiCorp apt signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp apt Repo
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution_major_version != "20"

- name: Add HashiCorp apt Repo
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com jammy main"
    state: present
  when: ansible_distribution_major_version == "20"

- name: Install Vault via apt
  apt:
    name: vault
    state: present
