- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Add HashiCorp yum repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault via yum
  yum:
    name: vault
    state: present
