- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Add HashiCorp yum repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: Fix Hashicorp yum repo
  shell: |
    sed 's/\$releasever/{{ ansible_distribution_major_version }}/g' -i /etc/yum.repos.d/hashicorp.repo

- name: Install Vault via yum
  yum:
    name: vault
    state: present
