# Matches mongot_community_fixture_e2e_single_node.yml + ReplicaSetFixture defaults.

net:
  port: 27017
  bindIpAll: true

replication:
  replSetName: rs

security:
  keyFile: /etc/mongodb/keyfile

setParameter:
  enableTestCommands: 1
  featureFlagEgressGrpcForSearch: true
  useGrpcForSearch: 1
  skipAuthenticationToMongot: true
  mongotHost: mongot:27028
  searchIndexManagementHostAndPort: mongot:27028

storage:
  dbPath: /var/lib/mongo

systemLog:
  destination: file
  path: /var/lib/mongo/mongod.log
  logAppend: true

processManagement:
  fork: false
