---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rocky9-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: "${MOLECULE_ROCKY9_AMI:-ami-0fadb4bc4d6071e9e}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: rocky
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
    converge: ../../playbooks/redhat.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: rocky9
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
