- name: Converge
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - set_fact:
        # Version of psmdb release to be enabled (psmdb-70)
        psmdb_to_test: "{{ lookup('env', 'PSMDB') | default('psmdb-80', true) }}"

    - set_fact:
        # Github token to access clustersync repo
        token: "{{ lookup('env', 'MONGO_REPO_TOKEN') }}"

    - set_fact:
        # Version of psmdb (v7.0, latest)
        psmdb_version: "{{ lookup('env', 'PSMDB_VERSION') | default('latest', true) }}"

    - set_fact:
        # Version of mongosh
        psmdb_mongosh: "{{ psmdb_to_test.split('-')[1].split('.')[0] }}"

    - set_fact:
        # Branch of pcsm branch to test
        pcsm_branch: "{{ lookup('env', 'pcsm_BRANCH') | default('main', true) }}"

    - set_fact:
        # Branch of pcsm branch to test
        golang_version: "{{ lookup('env', 'GO_VERSION') | default('1.24.2', true) }}"

    - name: Prerequisite for debian 11
      apt:
        name: iproute2
        update_cache: yes
      when: ansible_distribution == "Debian" and ansible_distribution_major_version >= "11"

    - name: Install deps
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - make
          - wget
          - git
      when: ansible_os_family == "RedHat"

    - name: Install deps
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - make
          - wget
          - git
          - iputils-ping
      when: ansible_os_family == "Debian"

    - name: Install Go from official tarball on pcsm host
      become: yes
      vars:
        go_version: "{{ golang_version }}"
        go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
        go_url: "https://go.dev/dl/{{ go_tarball }}"
        go_install_dir: "/usr/local"
      block:
        - name: Download Go {{ go_version }}
          get_url:
            url: "{{ go_url }}"
            dest: "/tmp/{{ go_tarball }}"
            mode: "0644"

        - name: Extract Go
          unarchive:
            src: "/tmp/{{ go_tarball }}"
            dest: "{{ go_install_dir }}"
            remote_src: yes
      when: inventory_hostname == "jenkins-pcsm-clustersync" or inventory_hostname == "jenkins-pcsm-source"

    - name: Check Go is available
      command: go version
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      register: go_version_output
      ignore_errors: true
      when: inventory_hostname == "jenkins-pcsm-clustersync" or inventory_hostname == "jenkins-pcsm-source"

    - name: Clone pcsm repo
      timeout: 180
      git:
        repo: "https://{{ token }}@github.com/percona/percona-clustersync-mongodb.git"
        dest: /tmp/percona-clustersync-mongodb
        version: "{{ pcsm_branch }}"
      when: inventory_hostname == "jenkins-pcsm-clustersync"

    - name: Build pcsm
      command: make build
      args:
        chdir: /tmp/percona-clustersync-mongodb
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOROOT: /usr/local/go/
        GOBIN: /usr/local/go/bin
      when: inventory_hostname == "jenkins-pcsm-clustersync"

    - name: Move clustersync binary to /usr/local/bin
      copy:
        src: /tmp/percona-clustersync-mongodb/bin/pcsm
        dest: /usr/local/bin/
        mode: "0755"
        remote_src: true
      when: inventory_hostname == "jenkins-pcsm-clustersync"

    - name: Clone Mgodatagen repo
      git:
        repo: "https://github.com/feliixx/mgodatagen.git"
        dest: /tmp/mgodatagen
        version: "master"
      when: inventory_hostname == "jenkins-pcsm-source"

    - name: Build Mgodatagen
      command: go build
      args:
        chdir: /tmp/mgodatagen
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOROOT: /usr/local/go/
        GOBIN: /usr/local/go/bin
      when: inventory_hostname == "jenkins-pcsm-source"

    - name: Move mgodatagen binary to /usr/local/bin
      copy:
        src: /tmp/mgodatagen/
        dest: /usr/local/bin/
        mode: "0755"
        remote_src: true
      when: inventory_hostname == "jenkins-pcsm-source"

    - name: Get private source ip address
      set_fact:
        private_source_ip: "{{ hostvars['jenkins-pcsm-source']['ansible_default_ipv4']['address'] }}"

    - name: Get private destination ip address
      set_fact:
        private_destination_ip: "{{ hostvars['jenkins-pcsm-destination']['ansible_default_ipv4']['address'] }}"

    - name: Add source and destination to /etc/hosts in pcsm
      blockinfile:
        path: /etc/hosts
        block: |
          {{ private_source_ip }}    source
          {{ private_destination_ip }}    destination
        create: false
        unsafe_writes: true
      when: inventory_hostname == "jenkins-pcsm-clustersync"

    - name: Install GPG key for epel 8
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and inventory_hostname in groups['psmdb']

    - name: Install GPG key for Percona repos
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and inventory_hostname in groups['psmdb']

    - name: Install percona repository package
      apt:
        deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
      when: ansible_os_family == "Debian" and inventory_hostname in groups['psmdb']

    - name: Install latest percona-release RHEL
      command: yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      when: ansible_os_family == "RedHat" and inventory_hostname in groups['psmdb']

    - name: setup psmdb repo with percona-release
      command: percona-release enable {{ psmdb_to_test }} release
      when: inventory_hostname in groups['psmdb']

    - name: Install psmdb deb packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - percona-server-mongodb
          - percona-server-mongodb-server
          - percona-server-mongodb-mongos
          - percona-server-mongodb-tools
      when: ansible_os_family == "Debian" and inventory_hostname in groups['psmdb']

    - name: Install latest psmdb rpm packages on redhat
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - percona-server-mongodb
          - percona-server-mongodb-server
          - percona-server-mongodb-mongos
          - percona-server-mongodb-tools
      when: ansible_os_family == "RedHat" and psmdb_version == "latest" and inventory_hostname in groups['psmdb']

    - name: Install less than latest psmdb rpm packages on redhat
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - percona-server-mongodb-{{ psmdb_version }}
          - percona-server-mongodb-server-{{ psmdb_version }}
          - percona-server-mongodb-mongos-{{ psmdb_version }}
          - percona-server-mongodb-tools-{{ psmdb_version }}
      when: ansible_os_family == "RedHat" and psmdb_version != "latest" and inventory_hostname in groups['psmdb']

    - name: Install mongo shell deb package
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - percona-server-mongodb-shell
      when: ansible_os_family == "Debian" and psmdb_mongosh < "6" and inventory_hostname in groups['psmdb']

    - name: Install mongosh deb package
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - percona-mongodb-mongosh
      when: ansible_os_family == "Debian" and psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: install mongo shell rpm package
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - percona-server-mongodb-shell
      when: ansible_os_family == "RedHat" and psmdb_mongosh < "6"

    - name: Install mongosh rpm package
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - percona-mongodb-mongosh
      when: ansible_os_family == "RedHat" and psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: Copy mongosh binary to mongo path for test scripts
      file:
        src: /usr/bin/mongosh
        dest: /usr/bin/mongo
        state: link
      when: psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: stop mongod service
      service: name=mongod state=stopped
      when: inventory_hostname in groups['psmdb']

    - name: Create data directory for mongod
      file:
        path: /mnt/data/db
        state: directory
        mode: "0755"
        owner: mongod
        group: mongod
      when: inventory_hostname in groups['psmdb']

    - name: Switch mongod to new dbPath
      replace:
        path: /etc/mongod.conf
        regexp: "^  dbPath: /var/lib/mongo(?:db)?"
        replace: "  dbPath: /mnt/data/db"
      when: inventory_hostname in groups['psmdb']

    - name: Add replica set name into mongod config
      replace:
        path: /etc/mongod.conf
        regexp: "^#replication:"
        replace: 'replication:\n  replSetName: "rs"'
      when: inventory_hostname in groups['psmdb']

    - name: Bind mongod to 0.0.0.0
      replace:
        path: /etc/mongod.conf
        regexp: "^  bindIp: 127.0.0.1"
        replace: "  bindIp: 0.0.0.0"
      when: inventory_hostname in groups['psmdb']

    - name: start mongod service
      service: name=mongod state=started
      when: inventory_hostname in groups['psmdb']

    - name: Install pymongo
      pip:
        name: pymongo

    - name: Create a replicaset rs
      community.mongodb.mongodb_replicaset:
        replica_set: rs
        login_host: "{{ private_source_ip }}"
        members:
          - host: "{{ private_source_ip }}:27017"
            priority: 1
        validate: no
      when: inventory_hostname == "jenkins-pcsm-source"

    - name: Create a replicaset rs
      community.mongodb.mongodb_replicaset:
        replica_set: rs
        login_host: "{{ private_destination_ip }}"
        members:
          - host: "{{ private_destination_ip }}:27017"
            priority: 1
        validate: no
      when: inventory_hostname == "jenkins-pcsm-destination"

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: inventory_hostname in groups['psmdb']

    - name: Create pcsm system unit file
      ansible.builtin.copy:
        dest: /etc/systemd/system/pcsm.service
        content: |
          [Unit]
          Description=Percona Clustersync Service
          After=network.target
  
          [Service]
          ExecStart=/usr/local/bin/pcsm --source mongodb://{{ private_source_ip }}:27017 --target mongodb://{{ private_destination_ip }}:27017
          Restart=on-failure
          User=root
  
          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: "0644"
      when: inventory_hostname == "jenkins-pcsm-clustersync"

    - name: Reload systemd and start pcsm service
      ansible.builtin.service:
        daemon_reload: yes
        name: pcsm.service
        state: started
      when: inventory_hostname == "jenkins-pcsm-clustersync"
