---
- name: Prepare node for running tests
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tasks:

  - name: Remove bullseye-backports entries from apt sources
    replace:
      path: /etc/apt/sources.list
      regexp: '^(deb.*bullseye-backports)'
      replace: '# \1'
    when: ansible_distribution_release == 'bullseye'

  - name: Check if there are broken CentOS7 repos
    stat:
      path: /etc/yum.repos.d/CentOS-Base.repo
    register: repo_file

  - name: fix repos for CentOS7
    shell:
      cmd: |
       sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/CentOS-Base.repo
       sed -i 's/^#.*baseurl=http/baseurl=http/g' /etc/yum.repos.d/CentOS-Base.repo
       sed -i 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/CentOS-Base.repo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" and repo_file.stat.exists

  - name: install GPG key for epel 7
    rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: setup epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Install necessary rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bzip2-devel
      - bzip2-libs
      - gcc
      - gcc-c++ 
      - git
      - make
      - openssl-devel
      - openssl11-devel
      - ncurses-devel
      - openssl-static
      - readline-devel
      - readline-static
      - sqlite-devel
      - zlib-devel
      - python-setuptools
      - python3
      - python3-devel
      - python3-pip
      - libffi-devel
      - xz-devel
      - unzip
      - epel-release
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install necessary rpm packages for RHEL8+
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - iproute
      - bzip2-devel
      - bzip2-libs
      - gcc
      - gcc-c++
      - git
      - make
      - openssl-devel
      - zlib-devel
      - curl
      - python3-pip
      - python3-devel
      - python3-ldap
      - psmisc
      - libffi-devel
      - xz-devel
      - unzip
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: install necessary rpm packages for AL
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - iproute
      - tar
      - bzip2-devel
      - bzip2-libs
      - gcc
      - gcc-c++
      - git
      - make
      - openssl
      - openssl-devel
      - zlib-devel
      - python3-pip
      - python3-devel
      - python3-ldap
      - psmisc
      - libffi-devel
      - xz-devel
      - unzip
    when: ansible_distribution == "Amazon"

  - name: install necessary rpm packages for RHEL9
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - openldap-compat
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: Update apt cache
    shell: apt update --allow-releaseinfo-change
    when: ansible_os_family == "Debian"

  - name: Install necessary deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - dirmngr
      - net-tools
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - libffi-dev
      - make
      - zlib1g-dev
      - python3
      - python3-pip
      - python3-dev
      - unzip
    when: ansible_os_family == "Debian"

  - set_fact:
      tarball: "{{ lookup('env', 'TARBALL') | default('https://downloads.percona.com/downloads/TESTING/psmdb-6.0.16/percona-server-mongodb-6.0.16-13-x86_64.glibc2.17-minimal.tar.gz', true) }}"

  - name: Get mongodb major version
    set_fact:
      mongodb_version: "{{ tarball | regex_search('mongodb-([0-9]+\\.[0-9]+)', '\\1') }}"

  - set_fact:
      python_version: "{{ lookup('env', 'PYTHON_VERSION') | default('3.10.14', true) }}"
    when: mongodb_version[0] | float >= 6.0

  - set_fact:
      python_version: "{{ lookup('env', 'PYTHON_VERSION') | default('3.8.19', true) }}"
    when: mongodb_version[0] | float <= 5.0

  - name: Download python
    get_url:
      url: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz
      dest: /opt/python.tar.gz

  - name: Extract python sources
    unarchive:
      src: /opt/python.tar.gz
      dest: /opt
      remote_src: yes

  - name: Fix for centos7
    shell: "sed -i 's/PKG_CONFIG openssl /PKG_CONFIG openssl11 /g' configure"
    args:
      chdir: /opt/Python-{{ python_version }}
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Configure python
    shell: "./configure --prefix=/opt/python --enable-optimizations"
    args:
      chdir: /opt/Python-{{ python_version }}

  - name: Install python
    shell: "make -j2 install"
    args:
      chdir: /opt/Python-{{ python_version }}

  - name: Install virtualenv 
    pip:
      name:
        - virtualenv
      state: latest
      executable: /opt/python/bin/pip3

  - name: Upgrade pip and create venv
    pip:
      name:
        - pip
      state: latest
      virtualenv: /opt/venv
      virtualenv_command: /opt/python/bin/virtualenv
      virtualenv_python: /opt/python/bin/python3

- set_fact:
    ssh_pubkey: "{{ lookup('env', 'SSH_PUBKEY') | default('none', true) }}"

- set_fact:
    ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

- name: Add user to Redhat
  user:
    name: "{{ ssh_user }}"
    shell: /bin/bash
    groups: wheel
    append: yes
  when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'RedHat'

- name: Add user to Debian
  user:
    name: "{{ ssh_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'Debian'

- name: Add pub key
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ ssh_pubkey }}"
  when: ssh_user != "none" and ssh_pubkey != "none"

- name: Allow sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'RedHat'

- name: Allow sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'Debian'


