---
- name: Prepare node for running tests
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
  - name: Install necessary packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bzip2-devel
      - bzip2-libs
      - gcc
      - git
      - make
      - openssl-devel
      - openssl-static
      - readline-devel
      - readline-static
      - sqlite-devel
      - zlib-devel
      - python-setuptools
      - python3
      - python3-devel
      - python3-pip
      - bzip2-devel
      - libffi-devel
      - xz-devel
    when: ansible_os_family == "RedHat"

  - name: Install necessary deb packages for debian 11
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - net-tools
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
      - python3
      - python3-pip
      - python3-dev
      - python3-markdown
      - python3-virtualenv
    when: ansible_distribution == "Debian"

  - name: Clone python repo
    git:
      repo: 'https://github.com/python/cpython.git'
      dest: /cpython
      version: "3.7"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
   
  - name: Configure python
    shell: "./configure --enable-optimizations"
    args:
      chdir: /cpython
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Install python
    shell: "make install"
    args:
      chdir: /cpython
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Ensure python
    file:
      src: /usr/local/bin/python3.7
      dest: /bin/python3
      state: link
      force: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Ensure pip
    file:
      src: /usr/local/bin/pip3.7
      dest: /usr/local/bin/pip3
      state: link
      force: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Ensure pip
    file:
      src: /usr/local/bin/pip3.7
      dest: /bin/pip3
      state: link
      force: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

