---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: PML-rhel8-arm-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: "${MOLECULE_RHEL8_ARM_AMI:-ami-0bb199dd39edd7d71}"
    vpc_subnet_id: subnet-0dc7518100473f19d
    instance_type: c6g.large
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    prepare: ../../playbooks/prepare.yml
    destroy: ../../../../playbooks/destroy.yml
    converge: ../../playbooks/redhat.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: rhel8-arm
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - cleanup
    - destroy
