services:
  psmdb:
    image: ${IMAGE:-percona/percona-server-mongodb}
    container_name: psmdb
    hostname: psmdb
    user: root
    entrypoint: mongod
    command: " --bind_ip_all --tlsMode requireTLS --tlsCertificateKeyFile /etc/x509/psmdb.pem --tlsCAFile /etc/x509/ca.crt --tlsAllowConnectionsWithoutCertificates"
    networks:
      - test
    volumes:
      - x509:/etc/x509

  ycsb:
    image: ycsb/local
    build:
      dockerfile: ./Dockerfile_ycsb
      context: .
    container_name: ycsb
    hostname: ycsb
    entrypoint: bin/ycsb.sh
    environment:
      - "JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/x509/cacert.jks -Djavax.net.ssl.trustStorePassword=changeit"
    command: " load mongodb -s -P /ycsb/workloads/workloada -p recordcount=100 -threads 100 -p mongodb.url='mongodb://psmdb:27017/ycsb?tls=true'"
    networks:
      - test
    volumes:
      - x509:/etc/x509

  easyrsa:
    image: easyrsa/local
    build:
      dockerfile: ./Dockerfile_easyrsa
      context: .
    container_name: easyrsa
    hostname: easyrsa
    networks:
      - test
    volumes:
      - x509:/etc/x509

volumes:
  x509:
    name: x509

networks:
  test:
    name: test
