---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: psmdb
    - role: '../../../roles/openldap'
#      when: not ( ansible_architecture == "aarch64" or ansible_architecture == "arm64" )
    - role: '../../../roles/kerberos'
