---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: '../../../roles/easyrsa'
    - role: psmdb
    - role: '../../../roles/docker'
    - role: '../../../roles/easyrsa'
    - role: '../../../roles/openldap'
    - role: '../../../roles/kmip-vault'
    - role: '../../../roles/kerberos-docker'
