---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_OS:-ubuntu2204}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  additional_files_or_dirs:
    - ../psmdb/tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: docker
  test_sequence:
    - converge
    - verify
