---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_OS:-rocky9}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-rockylinux9-ansible:latest}"
    dockerfile: Dockerfile
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        ansible_become_method: su
  playbooks:
    converge: ../../playbooks/playbook.yml
    prepare: ../../../../playbooks/prepare.yml
verifier:
  name: testinfra
  directory: ../../tests/
#  additional_files_or_dirs:
#    - ../psmdb/tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: docker
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
