---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_OS:-source}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    ssh_user: root
  - name: ${MOLECULE_OS:-source}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    ssh_user: root
  - name: ${MOLECULE_OS:-pml}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    ssh_user: root
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../playbooks/playbook.yml
    prepare: ../../../../playbooks/prepare.yml
verifier:
  name: testinfra
  directory: ../../tests/
#  additional_files_or_dirs:
#    - ../psmdb/tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: docker
  test_sequence:
    - converge
    - verify
