---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel8-arm-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-0bb199dd39edd7d71
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: a1.large
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  additional_files_or_dirs:
    - ../psmdb/tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: rhel8-arm
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
