---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_OS:-amazonlinux2023}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-amazonlinux2023-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
    cleanup: ../../playbooks/cleanup.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
#    s: true
    capture: sys
    o: junit_logging=system-out
    junitxml: ${MOLECULE_OS:-ubuntu}-report.xml
scenario:
  name: docker
  test_sequence:
    - prepare
    - converge
    - verify
