---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${MOLECULE_OS:-ubuntu2204}
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
#  - name: ${MOLECULE_OS:-centos7}
#    image: "${MOLECULE_DISTRO:-geerlingguy/docker-centos7-ansible:latest}"
#  - name: ${MOLECULE_OS:-ubuntu}
#    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible:latest}"

    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
    cleanup: ../../playbooks/cleanup.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
#    s: true
    capture: sys
    o: junit_logging=system-out
    junitxml: ${MOLECULE_OS:-ubuntu}-report.xml
scenario:
  name: docker
  test_sequence:
    - prepare
    - converge
    - verify
