- set_fact:
    ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when:
    - ansible_os_family == "Debian"

- name: Download Docker GPG key to keyring
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when:
    - ansible_os_family == "Debian"

- name: Map architecture for Docker APT repo
  set_fact:
    docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else
                  'arm64' if ansible_architecture == 'aarch64' }}"

- name: Write Docker apt source
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
    content: |
      deb [arch={{ (ansible_architecture == 'x86_64') | ternary('amd64', (ansible_architecture == 'aarch64') | ternary('arm64', ansible_architecture)) }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }} {{ ansible_distribution_release }} stable

- name: Update apt cache
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - git
      - python3-pip
      - wget
      - iputils-ping
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: ansible_os_family == "Debian"

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user ssh-user to docker group
  user:
    name: "{{ ssh_user }}"
    groups: docker
    append: yes
