- name: Print the OS family
  debug:
    msg: "OS Family is: {{ ansible_os_family }}"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat']