- set_fact:
    # User to log into each AWS Instance
    ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

- name: Remove podman-docker if present
  yum:
    name: podman-docker
    state: absent
  when: ansible_os_family == "RedHat"

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  when:
    - ansible_os_family == "RedHat"

- name: Force release server to use 9 in Docker repo for AL2023 compatibility
  replace:
    path: /etc/yum.repos.d/docker-ce.repo
    regexp: '\$releasever'
    replace: '9'
  when:
    - ansible_distribution == "Amazon"

- name: Install dependencies
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - wget
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: ansible_os_family == "RedHat"

- name: Install Percona Release
  include_tasks: ../../../tasks/install_percona_release.yml

- name: Setup plm repo with percona-release
  command: percona-release enable plm {{ lookup('env', 'install_repo') }}

- name: Install PLM
  yum:
    name: percona-link-mongodb
    update_cache: yes
    state: latest

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Set runc binary URL based on architecture
  set_fact:
    runc_url: >-
      https://github.com/opencontainers/runc/releases/download/v1.1.12/{{
        'runc.arm64' if ansible_architecture == 'aarch64' else 'runc.amd64'
      }}

- name: Download correct runc binary
  get_url:
    url: "{{ runc_url }}"
    dest: /usr/local/bin/runc
    mode: '0755'

- name: Move runc to /usr/bin
  copy:
    src: /usr/local/bin/runc
    dest: /usr/bin/runc
    remote_src: yes
    mode: '0755'
    force: yes

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user ssh-user to docker group
  user:
    name: "{{ ssh_user }}"
    groups: docker
    append: yes