- name: Prepare
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - set_fact:
        ssh_pubkey: "{{ lookup('env', 'SSH_PUBKEY') | default('none', true) }}"

    - set_fact:
        ssh_user: "{{ lookup('env', 'SSH_USER') | default('none', true) }}"

    - name: Add user to Redhat
      user:
        name: "{{ ssh_user }}"
        shell: /bin/bash
        groups: wheel
        append: yes
      when:
        - ssh_user != "none"
        - ssh_pubkey != "none"
        - ansible_facts['os_family'] == 'RedHat'

    - name: Add user to Debian
      user:
        name: "{{ ssh_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
      when:
        - ssh_user != "none"
        - ssh_pubkey != "none"
        - ansible_facts['os_family'] == 'Debian'

    - name: Add pub key
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ ssh_pubkey }}"
      when: ssh_user != "none" and ssh_pubkey != "none"

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'RedHat'

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      when: ssh_user != "none" and ssh_pubkey != "none" and ansible_facts['os_family'] == 'Debian'

    - name: Remove bullseye-backports entries from apt sources
      replace:
        path: /etc/apt/sources.list
        regexp: '^(deb.*bullseye-backports)'
        replace: '# \1'
      when: ansible_distribution_release == 'bullseye'
