---
# tasks file for PSMDB
- name: prerequisite for debian 11
  apt:
    name: iproute2
    update_cache: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"      

- name: get primary ip adrress
  set_fact: 
    rs0_primary_ip: "{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] }}"
  when: inventory_hostname in groups['primary']

- debug:
    msg: "{{rs0_primary_ip}}"
  when: inventory_hostname in groups['primary']

- set_fact: 
    rs0_secondary_ips: "{% for host in groups['secondary'] %}{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}{% if not loop.last %},{% endif %}{% endfor %}"

- debug:
    msg: "{{rs0_secondary_ips}}"

- set_fact:
    new_tarball: "{{ lookup('env', 'NEW_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-4.2/percona-server-mongodb-4.2.15-16/binary/tarball/percona-server-mongodb-4.2.15-16-x86_64.glibc2.17-minimal.tar.gz', true) }}"

- set_fact:
    storage: "{{ lookup('env', 'STORAGE') | default('wiredTiger', true) }}"    

- name: check correct storage
  fail: 
    msg: incorrect storage type {{ storage }}
  when: storage != "wiredTiger" and storage != "inMemory"  

- set_fact:
    encryption: "{{ lookup('env', 'ENCRYPTION') | default('NONE', true) }}"
  when: storage == "wiredTiger"   

- name: check correct encryption
  fail:
    msg: incorrect encryption {{ encryption }}
  when: encryption != "NONE" and encryption != "VAULT" and encryption != "KEYFILE"

- set_fact:
    encryption: "NONE"
  when: storage == "inMemory"

- set_fact:
    cipher: "{{ lookup('env', 'CIPHER') | default('AES256-CBC', true) }}"

- set_fact:
    keyfile: "/package-testing/scripts/psmdb_encryption/mongodb-keyfile"

- set_fact:
    vault_token: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"

- set_fact:
    vault_cert: "/package-testing/scripts/psmdb_encryption/test.cer"

- set_fact:
    vault_secret: "secret_v2/data/psmdb-test/package-test"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --encryptionKeyFile {{ keyfile }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "KEYFILE"

- set_fact:
    mongo_opts: " --wiredTigerCacheSizeGB 0.25 --enableEncryption --vaultServerName 127.0.0.1 --vaultPort 8200 --vaultTokenFile {{ vault_token }} --vaultSecret {{ vault_secret }} --vaultServerCAFile {{ vault_cert }} --encryptionCipherMode {{  cipher }}"
  when: encryption == "VAULT"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --wiredTigerCacheSizeGB 0.25"
  when: encryption == "NONE" and storage == "wiredTiger"

- set_fact:
    mongo_opts: " --storageEngine {{ storage }} --inMemorySizeGB 0.25"
  when: encryption == "NONE" and storage == "inMemory"

- name: Create data directories
  file:
    path: /usr/share/man/man1
    state: directory
    mode: 0775
   
- name: install necessary deb packages for ubuntu xenial
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl3
    - python3-pip 
    - python3-dev
    - python3-markdown
    - psmisc 
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: install necessary deb packages for ubuntu
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python3-pip
    - python3-dev
    - python3-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16"

- name: install necessary deb packages for debian 9
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl3
    - python-pip
    - python-dev
    - python-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- name: install necessary deb packages for debian 10
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python-pip
    - python-dev
    - python-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

- name: install necessary deb packages for debian 11
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - libcurl4
    - python3-pip
    - python3-dev
    - python3-markdown
    - psmisc
    - gcc
    - default-jre
    - default-jdk
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"

- name: install necessary rpm packages for Centos7
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - curl
    - libcurl
    - python-pip
    - python-devel
    - python-markdown
    - psmisc
    - gcc
    - java
    - java-devel
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install necessary rpm packages for RHEL8
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - curl
    - python3-pip
    - python3-devel
    - python3-markdown
    - psmisc
    - gcc
    - java
    - java-devel
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Install necessary python package
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - pymongo 
    - subprocess32 
    - PyYAML 
    - typing 
    - requests 
    - Cheetah3 
    - regex 
    - awscli
    - boto
    - boto3
    - botocore

- name: Create workdir
  file:
    path: /workdir
    state: directory
    mode: '0755'

- name: Download new tarball
  get_url:
    url: '{{ new_tarball }}'
    dest: /tmp/percona-server-mongodb-new.tar.gz
    mode: '0644'

- name: Unpack new tarball
  unarchive: 
    src: /tmp/percona-server-mongodb-new.tar.gz
    dest: /                     
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/mongo-new-bindir,S'

- name: Download testing dir
  git:
    repo: 'https://github.com/Percona-QA/psmdb-testing.git'
    dest: /package-testing
    version: PSMDB-919_tarball-tests

- name: Download test database
  get_url:
    url: https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json
    dest: /workdir/primer-dataset.json    
    mode: '0644'

- name: Download mongo driver
  get_url:
    url: https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.1/mongo-java-driver-3.12.1.jar
    dest: /workdir/mongo-java-driver.jar
    mode: '0644'

- name: Download sysbench test
  git:
    repo: 'https://github.com/Percona-Lab/sysbench-mongodb.git'
    dest: /workdir/sysbench-mongodb

- name: Download ycsb test
  get_url:
    url: 'https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-mongodb-binding-0.17.0.tar.gz'
    dest: /tmp/ycsb-mongodb-binding.tar.gz
    mode: '0644'    

- name: Unpack ycsb test
  unarchive:
    src: /tmp/ycsb-mongodb-binding.tar.gz
    dest: /workdir
    remote_src: yes
    extra_opts:
    - --transform
    - 's,^/*[^/]*,/ycsb-mongodb-binding,S'

- name: Download mgodatagen
  get_url:
    url: 'https://github.com/feliixx/mgodatagen/releases/download/v0.9.2/mgodatagen_0.9.2_Linux_x86_64.tar.gz'
    dest: /tmp/mgodatagen.tar.gz
    mode: '0644'

- name: Unpack mgodatagen
  unarchive:
    src: /tmp/mgodatagen.tar.gz
    dest: /workdir
    remote_src: yes

- name: Install and configure vault
  include_tasks: ../../../tasks/install_and_configure_vault.yml
  when: encryption == "VAULT"

- name: Ensure keyfile has correct permissions
  file:
    path: "{{ keyfile }}"
    mode: '0400'
  when: encryption == "KEYFILE"

- name: Ensure vault_cert has correct permissions
  file:
    path: "{{ vault_token }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Ensure vault_token has correct permissions
  file:
    path: "{{ vault_cert }}"                                            
    mode: '0400'
  when: encryption == "VAULT"

- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - /workdir/data

- name: Start replicaset
  command: "{{ item }}"
  with_items:    
    - /mongo-new-bindir/bin/mongod --fork --syslog --dbpath /workdir/data --port 27017 --bind_ip 0.0.0.0 --replSet rs0 {{ mongo_opts }}   

- name: Create a replicaset rs0
  community.mongodb.mongodb_replicaset:
    replica_set: rs0
    members:
    - host: "{{ rs0_primary_ip }}:27017"
      priority: 1
    - host: "{{ rs0_secondary_ips.split(',')[0] }}:27017"
      priority: 0.5
    - host: "{{ rs0_secondary_ips.split(',')[1] }}:27017"
      priority: 0.5
  when: inventory_hostname in groups['primary']
