- name: Converge
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - set_fact:
        # Version of psmdb release to be enabled (psmdb-70)
        psmdb_to_test: "{{ lookup('env', 'PSMDB') | default('main', true) }}"

    - set_fact:
        # Github token to access mongolink repo
        token: "{{ lookup('env', 'MONGO_REPO_TOKEN') }}"

    - set_fact:
        # Version of psmdb (v7.0, latest)
        psmdb_version: "{{ lookup('env', 'PSMDB_VERSION') | default('latest', true) }}"

    - set_fact:
        # Version of mongosh
        psmdb_mongosh: "{{ psmdb_to_test.split('-')[1].split('.')[0] }}"

    - set_fact:
        # Branch of pml branch to test
        pml_branch: "{{ lookup('env', 'PML_BRANCH') | default('main', true) }}"

    - set_fact:
        # Branch of pml branch to test
        golang_version: "{{ lookup('env', 'GO_VERSION') | default('main', true) }}"

    - name: prerequisite for debian 11
      apt:
        name: iproute2
        update_cache: yes
      when: ansible_distribution == "Debian" and ansible_distribution_major_version >= "11"      

    - name: Install deps
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - make
        - wget
        - git
      when: ansible_os_family == "RedHat"

    - name: Install deps
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - make
        - wget
        - git
        - iputils-ping
      when: ansible_os_family == "Debian"

    - name: Install Go from official tarball on PML host
      become: yes
      vars:
        go_version: "{{ golang_version }}"
        go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
        go_url: "https://go.dev/dl/{{ go_tarball }}"
        go_install_dir: "/usr/local"
      block:
        - name: Download Go {{ go_version }}
          get_url:
            url: "{{ go_url }}"
            dest: "/tmp/{{ go_tarball }}"
            mode: '0644'

        - name: Extract Go
          unarchive:
            src: "/tmp/{{ go_tarball }}"
            dest: "{{ go_install_dir }}"
            remote_src: yes
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: Check go availability
      command: go version
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      register: go_version_output
      ignore_errors: true
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: Clone PML repo
      timeout: 180
      git:
        repo: 'https://{{ token }}@github.com/Percona-Lab/percona-mongolink.git'
        dest: /tmp/percona-mongolink
        version: "{{ pml_branch }}"
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: Build PML
      command: make build
      args:
        chdir: /tmp/percona-mongolink
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOROOT: /usr/local/go/
        GOBIN: /usr/local/go/bin
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: Move mongolink binary to /usr/local/bin
      copy:
        src: /tmp/percona-mongolink/bin/percona-mongolink
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: true
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: Clone Mgodatagen repo
      git:
        repo: 'https://github.com/feliixx/mgodatagen.git'
        dest: /tmp/mgodatagen
        version: "master"
      when: inventory_hostname == "jenkins-pml-source"

    - name: Build Mgodatagen
      command: go build
      args:
        chdir: /tmp/mgodatagen
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOROOT: /usr/local/go/
        GOBIN: /usr/local/go/bin
      when: inventory_hostname == "jenkins-pml-source"

    - name: Move mgodatagen binary to /usr/local/bin
      copy:
        src: /tmp/mgodatagen/
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: true
      when: inventory_hostname == "jenkins-pml-source"

    - name: get source ip address
      set_fact:
          source_ip: "{{ hostvars['jenkins-pml-source']['ansible_facts']['default_ipv4']['address'] }}"

    - name: get destination ip address
      set_fact:
        destination_ip: "{{ hostvars['jenkins-pml-destination']['ansible_facts']['default_ipv4']['address'] }}"

    - name: Show source IP
      debug:
        var: source_ip
      when: destination_ip is defined and inventory_hostname == "jenkins-pml-source"

    - name: Show destination IP
      debug:
        var: destination_ip
      when: destination_ip is defined and inventory_hostname == "destination"

    - name: Add source and destination to /etc/hosts in pml
      blockinfile:
        path: /etc/hosts
        block: |
          {{ source_ip }}    source
          {{ destination_ip }}    destination
        create: false
        unsafe_writes: true
      when: inventory_hostname == "jenkins-pml-mongolink"

    - name: install GPG key for epel 8
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and inventory_hostname in groups['psmdb']

    - name: install GPG key for Percona repos
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and inventory_hostname in groups['psmdb']

    - name: Install percona repository package
      apt:
        deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
      when: ansible_os_family == "Debian" and inventory_hostname in groups['psmdb']

    - name: Install latest percona release RHEL
      command: yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      when: ansible_os_family == "RedHat" and inventory_hostname in groups['psmdb']

    - name: setup psmdb repo with percona-release
      command: percona-release enable {{ psmdb_to_test }} release
      when: inventory_hostname in groups['psmdb']

    - name: install psmdb deb packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-tools
      when: ansible_os_family == "Debian" and inventory_hostname in groups['psmdb']

    - name: install latest psmdb rpm packages on redhat
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb
        - percona-server-mongodb-server
        - percona-server-mongodb-mongos
        - percona-server-mongodb-tools
      when: ansible_os_family == "RedHat" and psmdb_version == "latest" and inventory_hostname in groups['psmdb']

    - name: install less than latest psmdb rpm packages on redhat
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - percona-server-mongodb-{{ psmdb_version }}
        - percona-server-mongodb-server-{{ psmdb_version }}
        - percona-server-mongodb-mongos-{{ psmdb_version }}
        - percona-server-mongodb-tools-{{ psmdb_version }}
      when: ansible_os_family == "RedHat" and psmdb_version != "latest" and inventory_hostname in groups['psmdb']

    - name: install mongo shell deb package
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - percona-server-mongodb-shell
      when: ansible_os_family == "Debian" and psmdb_mongosh < "6" and inventory_hostname in groups['psmdb']

    - name: install mongosh deb package
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - percona-mongodb-mongosh
      when: ansible_os_family == "Debian" and psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: install mongo shell rpm package
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - percona-server-mongodb-shell
      when: ansible_os_family == "RedHat" and psmdb_mongosh < "6"

    - name: install mongosh rpm package
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - percona-mongodb-mongosh
      when: ansible_os_family == "RedHat" and psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: copy mongosh binary to mongo path for test scripts
      file:
        src: /usr/bin/mongosh
        dest: /usr/bin/mongo
        state: link
      when: psmdb_mongosh >= "6" and inventory_hostname in groups['psmdb']

    - name: stop mongod service
      service: name=mongod state=stopped
      when: inventory_hostname in groups['psmdb']

    - name: create data directory for mongod
      file:
        path: /mnt/data/db
        state: directory
        mode: '0755'
        owner: mongod
        group: mongod
      when: inventory_hostname in groups['psmdb']

    - name: switch mongod to new dbPath
      replace:
        path: /etc/mongod.conf
        regexp: '^  dbPath: /var/lib/mongo(?:db)?'
        replace: '  dbPath: /mnt/data/db'
      when: inventory_hostname in groups['psmdb']

    - name: add replica set name into mongod config
      replace:
        path: /etc/mongod.conf
        regexp: '^#replication:'
        replace: 'replication:\n  replSetName: "rs"'
      when: inventory_hostname in groups['psmdb']

    - name: bind mongod to 0.0.0.0
      replace:
        path: /etc/mongod.conf
        regexp: '^  bindIp: 127.0.0.1'
        replace: '  bindIp: 0.0.0.0'
      when: inventory_hostname in groups['psmdb']

    - name: start mongod service
      service: name=mongod state=started
      when: inventory_hostname in groups['psmdb']

    - name: install pymongo
      pip:
        name: pymongo

    - name: Create a replicaset rs
      community.mongodb.mongodb_replicaset:
        replica_set: rs
        login_host: "{{ source_ip }}"
        members:
          - host: "{{ source_ip }}:27017"
            priority: 1
        validate: no
      when: inventory_hostname == "jenkins-pml-source"

    - name: Create a replicaset rs
      community.mongodb.mongodb_replicaset:
        replica_set: rs
        login_host: "{{ destination_ip }}"
        members:
          - host: "{{ destination_ip }}:27017"
            priority: 1
        validate: no
      when: inventory_hostname == "jenkins-pml-destination"

    - name: reload systemd
      systemd:
        daemon_reload: yes