{
 "title": "PCSM_all_metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "percona_clustersync_mongodb_copy_insert_batch_duration_seconds (in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_insert_batch_duration_seconds * 1000"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_copy_insert_document_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_insert_document_total"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_copy_insert_size_bytes_total (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_insert_size_bytes_total / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_copy_read_batch_duration_seconds (in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_batch_duration_seconds * 1000"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_copy_read_document_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_document_total"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_copy_read_size_bytes_total (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_size_bytes_total / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_estimated_total_size_bytes (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_estimated_total_size_bytes / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_events_applied_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_events_applied_total"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_initial_sync_lag_time_seconds (in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_initial_sync_lag_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_lag_time_seconds (in ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_lag_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_max_fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_max_fds"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_network_receive_bytes_total (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_network_receive_bytes_total / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_network_transmit_bytes_total (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_network_transmit_bytes_total / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_open_fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_open_fds"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_resident_memory_bytes (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_resident_memory_bytes / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_start_time_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_start_time_seconds"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_virtual_memory_bytes (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_virtual_memory_bytes / 1073741824"
    }
   ]
  },
  {
   "title": "percona_clustersync_mongodb_process_virtual_memory_max_bytes (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_process_virtual_memory_max_bytes / 1073741824"
    }
   ]
  }
 ]
}