{
 "title": "PCSM_sync_monitor",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(percona_clustersync_mongodb_copy_read_size_bytes_total[$__rate_interval]) / 1048576",
     "legendFormat": "read Mb/s"
    },
    {
     "expr": "rate(percona_clustersync_mongodb_copy_insert_size_bytes_total[$__rate_interval]) / 1048576",
     "legendFormat": "write Mb/s"
    }
   ]
  },
  {
   "title": "Bytes (in GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_size_bytes_total / 1073741824",
     "legendFormat": "Read"
    },
    {
     "expr": "percona_clustersync_mongodb_copy_insert_size_bytes_total / 1073741824",
     "legendFormat": "Write"
    },
    {
     "expr": "percona_clustersync_mongodb_estimated_total_size_bytes / 1073741824",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Duration in ms [per ~48MB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_batch_duration_seconds * 100",
     "legendFormat": "Read Batch"
    },
    {
     "expr": "percona_clustersync_mongodb_copy_insert_batch_duration_seconds * 100",
     "legendFormat": "Write Batch"
    }
   ]
  },
  {
   "title": "Memory Usage in MiB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes / 1048576",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "Total Documents Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_copy_read_document_total",
     "legendFormat": "Read"
    },
    {
     "expr": "percona_clustersync_mongodb_copy_insert_document_total",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_lag_time_seconds",
     "legendFormat": "Lag Time"
    },
    {
     "expr": "rate(percona_clustersync_mongodb_lag_time_seconds[$__rate_interval])",
     "legendFormat": "Lag Time Rate"
    }
   ]
  },
  {
   "title": "Lag Time in logical seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "percona_clustersync_mongodb_initial_sync_lag_time_seconds",
     "legendFormat": "Initial Sync"
    },
    {
     "expr": "percona_clustersync_mongodb_lag_time_seconds",
     "legendFormat": "Source TIme"
    }
   ]
  }
 ]
}