---
- name: Download packages to localhost
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - set_fact:
        old_tarball: "{{ lookup('env', 'OLD_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-4.2/percona-server-mongodb-4.2.15-16/binary/tarball/percona-server-mongodb-4.2.15-16-x86_64.glibc2.17-minimal.tar.gz', true) }}"
       
    - set_fact:
        new_tarball: "{{ lookup('env', 'NEW_TARBALL') | default('https://downloads.percona.com/downloads/percona-server-mongodb-LATEST/percona-server-mongodb-4.4.8-9/binary/tarball/percona-server-mongodb-4.4.8-9-x86_64.glibc2.17-minimal.tar.gz', true) }}"

    - name: Download old tarball
      get_url:
        url: '{{ old_tarball }}'
        dest: /tmp/percona-server-mongodb-old.tar.gz
        mode: '0644'
      when: new_tarball.startswith('http')

    - name: Download old tarball
      aws_s3:
        bucket: "{{ old_tarball | urlsplit('hostname') }}"
        object: "{{ old_tarball | urlsplit('path') }}"
        dest: /tmp/percona-server-mongodb-old.tar.gz
        mode: get
      when: new_tarball.startswith('s3')

    - name: Download new tarball
      get_url:
        url: '{{ new_tarball }}'
        dest: /tmp/percona-server-mongodb-new.tar.gz
        mode: '0644'
      when: new_tarball.startswith('http')

    - name: Download new tarball
      aws_s3:
        bucket: "{{ new_tarball | urlsplit('hostname') }}"
        object: "{{ new_tarball | urlsplit('path') }}"
        dest: /tmp/percona-server-mongodb-new.tar.gz
        mode: get
      when: new_tarball.startswith('s3')

- name: Converge
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: psmdb-tarball-upgrade
