name: PBM

on:
  workflow_dispatch:
    inputs:
      psmdb:
        description: "psmdb docker image"
        required: false
      pbm_branch:
        description: "pbm branch"
        required: false
      go_ver:
        description: "golang version"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test: [logical, physical, incremental]
    env:
      PSMDB: ${{ github.event.inputs.psmdb || 'percona/percona-server-mongodb' }}
      PBM_BRANCH: ${{ github.event.inputs.pbm_branch || 'dev' }}
      GO_VER: ${{ github.event.inputs.go_ver || 'bullseye' }}
      MAKE_TARGET: 'build-cover'      
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment with PSMDB ${{ env.PSMDB }} and PBM branch ${{ env.PBM_BRANCH }}
      run: |
        docker compose build
        docker compose up -d
      working-directory: ./pbm-functional/pytest
    - name: Test ${{ matrix.test }} backup/restore on PSMDB ${{ env.PSMDB }} PBM branch ${{ env.PBM_BRANCH }}
      run: |
        docker compose run --rm test pytest -s --junitxml=junit.xml -k ${{ matrix.test }}
      working-directory: ./pbm-functional/pytest
    - name: Print func coverage for ${{ matrix.test }} backup/restore PBM branch ${{ env.PBM_BRANCH }}
      run: |
        docker compose run --rm golang_reports go tool covdata func -i /gocoverdir/reports
      working-directory: ./pbm-functional/pytest
      if: success() || failure()
    - name: Print percent coverage for ${{ matrix.test }} backup/restore PBM branch ${{ env.PBM_BRANCH }}
      run: |
        docker compose run --rm golang_reports go tool covdata percent -i /gocoverdir/reports
      working-directory: ./pbm-functional/pytest
      if: success() || failure()
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() 
      with:
        report_paths: '**/junit.xml'
