name: PBM

on:
  workflow_dispatch:
    inputs:
      psmdb:
        description: "psmdb docker image"
        required: false
      pbm_branch:
        description: "pbm branch"
        required: false
      go_ver:
        description: "golang version"
        required: false

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test_sharded:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    env:
      PSMDB: ${{ github.event.inputs.psmdb || 'percona/percona-server-mongodb:4.4' }}
      PBM_BRANCH: ${{ github.event.inputs.pbm_branch || 'main' }}
      GO_VER: ${{ github.event.inputs.go_ver || 'latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Test on single sharded cluster
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose run test pytest -s --junitxml=test-sharded.xml --disable-warnings test_sharded.py
      working-directory: ./pbm-functional/pytest
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() 
      with:
        report_paths: '**/test-sharded.xml'

  test_fresh_sharded:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      PSMDB: ${{ github.event.inputs.psmdb || 'percona/percona-server-mongodb:4.4' }}
      PBM_BRANCH: ${{ github.event.inputs.pbm_branch || 'main' }}
      GO_VER: ${{ github.event.inputs.go_ver || 'latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Test backup/restore with fresh cluster 
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose run test pytest -s --junitxml=test-fresh-sharded.xml --disable-warnings test_fresh_sharded.py
      working-directory: ./pbm-functional/pytest
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() 
      with:
        report_paths: '**/test-fresh-sharded.xml'

  test_remap_sharded:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      PSMDB: ${{ github.event.inputs.psmdb || 'percona/percona-server-mongodb:4.4' }}
      PBM_BRANCH: ${{ github.event.inputs.pbm_branch || 'main' }}
      GO_VER: ${{ github.event.inputs.go_ver || 'latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Test backup/restore with remapping
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose run test pytest -s --junitxml=test-remap-sharded.xml --disable-warnings test_remap_sharded.py
      working-directory: ./pbm-functional/pytest
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() 
      with:
        report_paths: '**/test-remap-sharded.xml'
