name: PLM-FULL

on:
  workflow_dispatch:
    inputs:
      plm_branch:
        description: "plm branch"
        required: false
      go_ver:
        description: "golang version"
        required: false

  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
    paths:
      - 'plm-pytest/**'

jobs:
  test:
    # Will not run if item is a draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        psmdb: ["6.0", "7.0", "8.0"]
    env:
      PLM_BRANCH: ${{ github.event.inputs.plm_branch || 'main' }}
      GO_VER: ${{ github.event.inputs.go_ver || 'bullseye' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment with PSMDB ${{ matrix.psmdb }} and PLM branch ${{ env.PLM_BRANCH }}
      run: |
        PSMDB=perconalab/percona-server-mongodb:${{ matrix.psmdb }} docker compose build easyrsa
        PSMDB=perconalab/percona-server-mongodb:${{ matrix.psmdb }} docker compose build
        docker compose up -d
      working-directory: ./plm-pytest
    - name: Test ${{ matrix.test }} backup/restore on PSMDB ${{ matrix.psmdb }} and PBM branch ${{ env.PLM_BRANCH }}
      run: |
        docker compose run --rm test pytest -s --junitxml=junit.xml
      working-directory: ./plm-pytest
    - name: Print PLM logs
      if: failure()
      run: |
        docker logs plink
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/junit.xml'
