---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: primary-rs0
    groups:
      - mongo
      - primary
      - mc
    region: us-west-2
    image: ami-01ed306a12b7d1c96
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
  - name: secondary1-rs0                        
    groups:
      - mongo
      - secondary
    region: us-west-2
    image: ami-01ed306a12b7d1c96
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
  - name: secondary2-rs0
    groups:
      - mongo
      - secondary
    region: us-west-2
    image: ami-01ed306a12b7d1c96
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: ${INSTANCE_TYPE:-i3.large}
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-psmdb-worker
provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../../../../playbooks/create.yml
    prepare: ../../playbooks/prepare.yml
    converge: ../../playbooks/converge.yml
    cleanup: ../../playbooks/cleanup.yml
    destroy: ../../../../playbooks/destroy.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
    capture: sys
    o: junit_logging=system-out
#    s: true
    junitxml: report.xml
scenario:
  name: aws
  test_sequence:
    - create
#    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
